/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing BillingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BillingApiTests : IDisposable
    {
        private BillingApi instance;

        public BillingApiTests()
        {
            instance = new BillingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BillingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BillingApi
            //Assert.IsType<BillingApi>(instance);
        }

        /// <summary>
        /// Test CreateCheckoutSession
        /// </summary>
        [Fact]
        public void CreateCheckoutSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BillingCheckoutRequest billingCheckoutRequest = null;
            //var response = instance.CreateCheckoutSession(billingCheckoutRequest);
            //Assert.IsType<BillingCheckoutResponse>(response);
        }

        /// <summary>
        /// Test CreatePortalSession
        /// </summary>
        [Fact]
        public void CreatePortalSessionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.CreatePortalSession();
            //Assert.IsType<BillingPortalResponse>(response);
        }

        /// <summary>
        /// Test GetSubscription
        /// </summary>
        [Fact]
        public void GetSubscriptionTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetSubscription();
            //Assert.IsType<BillingSubscriptionResponse>(response);
        }

        /// <summary>
        /// Test ListPlans
        /// </summary>
        [Fact]
        public void ListPlansTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.ListPlans();
            //Assert.IsType<BillingPlansListResponse>(response);
        }

        /// <summary>
        /// Test UpdateOverageSettings
        /// </summary>
        [Fact]
        public void UpdateOverageSettingsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BillingOverageRequest billingOverageRequest = null;
            //var response = instance.UpdateOverageSettings(billingOverageRequest);
            //Assert.IsType<BillingOverageResponse>(response);
        }
    }
}
