/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing BrandingApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BrandingApiTests : IDisposable
    {
        private BrandingApi instance;

        public BrandingApiTests()
        {
            instance = new BrandingApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BrandingApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BrandingApi
            //Assert.IsType<BrandingApi>(instance);
        }

        /// <summary>
        /// Test DeleteLogoApiV1BrandingLogoDelete
        /// </summary>
        [Fact]
        public void DeleteLogoApiV1BrandingLogoDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.DeleteLogoApiV1BrandingLogoDelete();
            //Assert.IsType<SimpleBoolResponse>(response);
        }

        /// <summary>
        /// Test GetBrandingApiV1BrandingGet
        /// </summary>
        [Fact]
        public void GetBrandingApiV1BrandingGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //var response = instance.GetBrandingApiV1BrandingGet();
            //Assert.IsType<BrandingResponse>(response);
        }

        /// <summary>
        /// Test UpdateBrandingApiV1BrandingPut
        /// </summary>
        [Fact]
        public void UpdateBrandingApiV1BrandingPutTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BrandingUpdateRequest brandingUpdateRequest = null;
            //var response = instance.UpdateBrandingApiV1BrandingPut(brandingUpdateRequest);
            //Assert.IsType<BrandingResponse>(response);
        }

        /// <summary>
        /// Test UploadLogoApiV1BrandingLogoPost
        /// </summary>
        [Fact]
        public void UploadLogoApiV1BrandingLogoPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //var response = instance.UploadLogoApiV1BrandingLogoPost(file);
            //Assert.IsType<BrandingResponse>(response);
        }
    }
}
