/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing BusinessProfilesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class BusinessProfilesApiTests : IDisposable
    {
        private BusinessProfilesApi instance;

        public BusinessProfilesApiTests()
        {
            instance = new BusinessProfilesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of BusinessProfilesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' BusinessProfilesApi
            //Assert.IsType<BusinessProfilesApi>(instance);
        }

        /// <summary>
        /// Test CreateBusinessProfile
        /// </summary>
        [Fact]
        public void CreateBusinessProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //BusinessProfileCreate businessProfileCreate = null;
            //string? idempotencyKey = null;
            //var response = instance.CreateBusinessProfile(businessProfileCreate, idempotencyKey);
            //Assert.IsType<BusinessProfileResponse>(response);
        }

        /// <summary>
        /// Test DeleteBusinessProfile
        /// </summary>
        [Fact]
        public void DeleteBusinessProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string businessProfileId = null;
            //var response = instance.DeleteBusinessProfile(businessProfileId);
            //Assert.IsType<SimpleBoolResponse>(response);
        }

        /// <summary>
        /// Test GetBusinessProfile
        /// </summary>
        [Fact]
        public void GetBusinessProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string businessProfileId = null;
            //var response = instance.GetBusinessProfile(businessProfileId);
            //Assert.IsType<BusinessProfileResponse>(response);
        }

        /// <summary>
        /// Test ListBusinessProfiles
        /// </summary>
        [Fact]
        public void ListBusinessProfilesTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ListBusinessProfiles(limit, cursor);
            //Assert.IsType<BusinessProfilesListResponse>(response);
        }

        /// <summary>
        /// Test UpdateBusinessProfile
        /// </summary>
        [Fact]
        public void UpdateBusinessProfileTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string businessProfileId = null;
            //BusinessProfilePatch businessProfilePatch = null;
            //string? idempotencyKey = null;
            //var response = instance.UpdateBusinessProfile(businessProfileId, businessProfilePatch, idempotencyKey);
            //Assert.IsType<BusinessProfileResponse>(response);
        }
    }
}
