/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing CreditNotesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class CreditNotesApiTests : IDisposable
    {
        private CreditNotesApi instance;

        public CreditNotesApiTests()
        {
            instance = new CreditNotesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditNotesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' CreditNotesApi
            //Assert.IsType<CreditNotesApi>(instance);
        }

        /// <summary>
        /// Test CreateCreditNoteApiV1CreditNotesPost
        /// </summary>
        [Fact]
        public void CreateCreditNoteApiV1CreditNotesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //CreditNoteCreateRequest creditNoteCreateRequest = null;
            //var response = instance.CreateCreditNoteApiV1CreditNotesPost(creditNoteCreateRequest);
            //Assert.IsType<CreditNoteResponse>(response);
        }

        /// <summary>
        /// Test FinalizeCreditNoteApiV1CreditNotesCreditNoteIdFinalizePost
        /// </summary>
        [Fact]
        public void FinalizeCreditNoteApiV1CreditNotesCreditNoteIdFinalizePostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string creditNoteId = null;
            //var response = instance.FinalizeCreditNoteApiV1CreditNotesCreditNoteIdFinalizePost(creditNoteId);
            //Assert.IsType<CreditNoteResponse>(response);
        }

        /// <summary>
        /// Test GetCreditNoteApiV1CreditNotesCreditNoteIdGet
        /// </summary>
        [Fact]
        public void GetCreditNoteApiV1CreditNotesCreditNoteIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string creditNoteId = null;
            //var response = instance.GetCreditNoteApiV1CreditNotesCreditNoteIdGet(creditNoteId);
            //Assert.IsType<CreditNoteResponse>(response);
        }

        /// <summary>
        /// Test ListCreditNotesApiV1CreditNotesGet
        /// </summary>
        [Fact]
        public void ListCreditNotesApiV1CreditNotesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ListCreditNotesApiV1CreditNotesGet(limit, cursor);
            //Assert.IsType<CreditNotesListResponse>(response);
        }

        /// <summary>
        /// Test RenderCreditNoteApiV1CreditNotesCreditNoteIdRendersPost
        /// </summary>
        [Fact]
        public void RenderCreditNoteApiV1CreditNotesCreditNoteIdRendersPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string creditNoteId = null;
            //CreditNoteRenderRequest? creditNoteRenderRequest = null;
            //var response = instance.RenderCreditNoteApiV1CreditNotesCreditNoteIdRendersPost(creditNoteId, creditNoteRenderRequest);
            //Assert.IsType<Object>(response);
        }
    }
}
