/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing FilesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class FilesApiTests : IDisposable
    {
        private FilesApi instance;

        public FilesApiTests()
        {
            instance = new FilesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FilesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' FilesApi
            //Assert.IsType<FilesApi>(instance);
        }

        /// <summary>
        /// Test DeleteFileApiV1FilesFileIdDelete
        /// </summary>
        [Fact]
        public void DeleteFileApiV1FilesFileIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fileId = null;
            //var response = instance.DeleteFileApiV1FilesFileIdDelete(fileId);
            //Assert.IsType<SimpleBoolResponse>(response);
        }

        /// <summary>
        /// Test GetFileApiV1FilesFileIdGet
        /// </summary>
        [Fact]
        public void GetFileApiV1FilesFileIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string fileId = null;
            //var response = instance.GetFileApiV1FilesFileIdGet(fileId);
            //Assert.IsType<FileResponse>(response);
        }

        /// <summary>
        /// Test UploadFileApiV1FilesPost
        /// </summary>
        [Fact]
        public void UploadFileApiV1FilesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //System.IO.Stream file = null;
            //string? idempotencyKey = null;
            //var response = instance.UploadFileApiV1FilesPost(file, idempotencyKey);
            //Assert.IsType<FileResponse>(response);
        }
    }
}
