/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing NumberingSequencesApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class NumberingSequencesApiTests : IDisposable
    {
        private NumberingSequencesApi instance;

        public NumberingSequencesApiTests()
        {
            instance = new NumberingSequencesApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NumberingSequencesApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' NumberingSequencesApi
            //Assert.IsType<NumberingSequencesApi>(instance);
        }

        /// <summary>
        /// Test ConsumeNextApiV1NumberingSequencesSequenceIdNextPost
        /// </summary>
        [Fact]
        public void ConsumeNextApiV1NumberingSequencesSequenceIdNextPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sequenceId = null;
            //var response = instance.ConsumeNextApiV1NumberingSequencesSequenceIdNextPost(sequenceId);
            //Assert.IsType<NumberingSequenceResponse>(response);
        }

        /// <summary>
        /// Test CreateSequenceApiV1NumberingSequencesPost
        /// </summary>
        [Fact]
        public void CreateSequenceApiV1NumberingSequencesPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //NumberingSequenceCreateRequest numberingSequenceCreateRequest = null;
            //var response = instance.CreateSequenceApiV1NumberingSequencesPost(numberingSequenceCreateRequest);
            //Assert.IsType<NumberingSequenceResponse>(response);
        }

        /// <summary>
        /// Test DeleteSequenceApiV1NumberingSequencesSequenceIdDelete
        /// </summary>
        [Fact]
        public void DeleteSequenceApiV1NumberingSequencesSequenceIdDeleteTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sequenceId = null;
            //var response = instance.DeleteSequenceApiV1NumberingSequencesSequenceIdDelete(sequenceId);
            //Assert.IsType<SimpleBoolResponse>(response);
        }

        /// <summary>
        /// Test GetSequenceApiV1NumberingSequencesSequenceIdGet
        /// </summary>
        [Fact]
        public void GetSequenceApiV1NumberingSequencesSequenceIdGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sequenceId = null;
            //var response = instance.GetSequenceApiV1NumberingSequencesSequenceIdGet(sequenceId);
            //Assert.IsType<NumberingSequenceResponse>(response);
        }

        /// <summary>
        /// Test ListSequencesApiV1NumberingSequencesGet
        /// </summary>
        [Fact]
        public void ListSequencesApiV1NumberingSequencesGetTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ListSequencesApiV1NumberingSequencesGet(limit, cursor);
            //Assert.IsType<NumberingSequencesListResponse>(response);
        }

        /// <summary>
        /// Test PreviewSequenceApiV1NumberingSequencesSequenceIdPreviewPost
        /// </summary>
        [Fact]
        public void PreviewSequenceApiV1NumberingSequencesSequenceIdPreviewPostTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sequenceId = null;
            //var response = instance.PreviewSequenceApiV1NumberingSequencesSequenceIdPreviewPost(sequenceId);
            //Assert.IsType<NumberingSequencePreviewResponse>(response);
        }

        /// <summary>
        /// Test UpdateSequenceApiV1NumberingSequencesSequenceIdPatch
        /// </summary>
        [Fact]
        public void UpdateSequenceApiV1NumberingSequencesSequenceIdPatchTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string sequenceId = null;
            //NumberingSequencePatchRequest numberingSequencePatchRequest = null;
            //var response = instance.UpdateSequenceApiV1NumberingSequencesSequenceIdPatch(sequenceId, numberingSequencePatchRequest);
            //Assert.IsType<NumberingSequenceResponse>(response);
        }
    }
}
