/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using InvoicePDFs.Client;
using InvoicePDFs.Api;
// uncomment below to import models
//using InvoicePDFs.Model;

namespace InvoicePDFs.Test.Api
{
    /// <summary>
    ///  Class for testing PaymentsApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class PaymentsApiTests : IDisposable
    {
        private PaymentsApi instance;

        public PaymentsApiTests()
        {
            instance = new PaymentsApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PaymentsApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' PaymentsApi
            //Assert.IsType<PaymentsApi>(instance);
        }

        /// <summary>
        /// Test CreateDocumentPayment
        /// </summary>
        [Fact]
        public void CreateDocumentPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string documentId = null;
            //PaymentCreateRequest paymentCreateRequest = null;
            //var response = instance.CreateDocumentPayment(documentId, paymentCreateRequest);
            //Assert.IsType<PaymentResponse>(response);
        }

        /// <summary>
        /// Test DeletePayment
        /// </summary>
        [Fact]
        public void DeletePaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string paymentId = null;
            //var response = instance.DeletePayment(paymentId);
            //Assert.IsType<SimpleBoolResponse>(response);
        }

        /// <summary>
        /// Test GetPayment
        /// </summary>
        [Fact]
        public void GetPaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string paymentId = null;
            //var response = instance.GetPayment(paymentId);
            //Assert.IsType<PaymentResponse>(response);
        }

        /// <summary>
        /// Test ListDocumentPayments
        /// </summary>
        [Fact]
        public void ListDocumentPaymentsTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string documentId = null;
            //int? limit = null;
            //string? cursor = null;
            //var response = instance.ListDocumentPayments(documentId, limit, cursor);
            //Assert.IsType<PaymentsListResponse>(response);
        }

        /// <summary>
        /// Test UpdatePayment
        /// </summary>
        [Fact]
        public void UpdatePaymentTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //string paymentId = null;
            //PaymentPatchRequest paymentPatchRequest = null;
            //var response = instance.UpdatePayment(paymentId, paymentPatchRequest);
            //Assert.IsType<PaymentResponse>(response);
        }
    }
}
