/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing AuditEventOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AuditEventOutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AuditEventOut
        //private AuditEventOut instance;

        public AuditEventOutTests()
        {
            // TODO uncomment below to create an instance of AuditEventOut
            //instance = new AuditEventOut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AuditEventOut
        /// </summary>
        [Fact]
        public void AuditEventOutInstanceTest()
        {
            // TODO uncomment below to test "IsType" AuditEventOut
            //Assert.IsType<AuditEventOut>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Actor'
        /// </summary>
        [Fact]
        public void ActorTest()
        {
            // TODO unit test for the property 'Actor'
        }

        /// <summary>
        /// Test the property 'Action'
        /// </summary>
        [Fact]
        public void ActionTest()
        {
            // TODO unit test for the property 'Action'
        }

        /// <summary>
        /// Test the property 'ResourceType'
        /// </summary>
        [Fact]
        public void ResourceTypeTest()
        {
            // TODO unit test for the property 'ResourceType'
        }

        /// <summary>
        /// Test the property 'ResourceId'
        /// </summary>
        [Fact]
        public void ResourceIdTest()
        {
            // TODO unit test for the property 'ResourceId'
        }

        /// <summary>
        /// Test the property 'WorkspaceId'
        /// </summary>
        [Fact]
        public void WorkspaceIdTest()
        {
            // TODO unit test for the property 'WorkspaceId'
        }

        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }

        /// <summary>
        /// Test the property 'UserAgent'
        /// </summary>
        [Fact]
        public void UserAgentTest()
        {
            // TODO unit test for the property 'UserAgent'
        }

        /// <summary>
        /// Test the property 'RequestId'
        /// </summary>
        [Fact]
        public void RequestIdTest()
        {
            // TODO unit test for the property 'RequestId'
        }

        /// <summary>
        /// Test the property 'Summary'
        /// </summary>
        [Fact]
        public void SummaryTest()
        {
            // TODO unit test for the property 'Summary'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
