/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing CreditNoteCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreditNoteCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreditNoteCreateRequest
        //private CreditNoteCreateRequest instance;

        public CreditNoteCreateRequestTests()
        {
            // TODO uncomment below to create an instance of CreditNoteCreateRequest
            //instance = new CreditNoteCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreditNoteCreateRequest
        /// </summary>
        [Fact]
        public void CreditNoteCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreditNoteCreateRequest
            //Assert.IsType<CreditNoteCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'InvoiceId'
        /// </summary>
        [Fact]
        public void InvoiceIdTest()
        {
            // TODO unit test for the property 'InvoiceId'
        }

        /// <summary>
        /// Test the property 'CreditNoteNumber'
        /// </summary>
        [Fact]
        public void CreditNoteNumberTest()
        {
            // TODO unit test for the property 'CreditNoteNumber'
        }

        /// <summary>
        /// Test the property 'IssueDate'
        /// </summary>
        [Fact]
        public void IssueDateTest()
        {
            // TODO unit test for the property 'IssueDate'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'LineItems'
        /// </summary>
        [Fact]
        public void LineItemsTest()
        {
            // TODO unit test for the property 'LineItems'
        }
    }
}
