/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing DeliverySendRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DeliverySendRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DeliverySendRequest
        //private DeliverySendRequest instance;

        public DeliverySendRequestTests()
        {
            // TODO uncomment below to create an instance of DeliverySendRequest
            //instance = new DeliverySendRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DeliverySendRequest
        /// </summary>
        [Fact]
        public void DeliverySendRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" DeliverySendRequest
            //Assert.IsType<DeliverySendRequest>(instance);
        }

        /// <summary>
        /// Test the property 'To'
        /// </summary>
        [Fact]
        public void ToTest()
        {
            // TODO unit test for the property 'To'
        }

        /// <summary>
        /// Test the property 'Cc'
        /// </summary>
        [Fact]
        public void CcTest()
        {
            // TODO unit test for the property 'Cc'
        }

        /// <summary>
        /// Test the property 'Bcc'
        /// </summary>
        [Fact]
        public void BccTest()
        {
            // TODO unit test for the property 'Bcc'
        }

        /// <summary>
        /// Test the property 'Subject'
        /// </summary>
        [Fact]
        public void SubjectTest()
        {
            // TODO unit test for the property 'Subject'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'AttachPdf'
        /// </summary>
        [Fact]
        public void AttachPdfTest()
        {
            // TODO unit test for the property 'AttachPdf'
        }
    }
}
