/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing DocumentTypeOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class DocumentTypeOutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for DocumentTypeOut
        //private DocumentTypeOut instance;

        public DocumentTypeOutTests()
        {
            // TODO uncomment below to create an instance of DocumentTypeOut
            //instance = new DocumentTypeOut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of DocumentTypeOut
        /// </summary>
        [Fact]
        public void DocumentTypeOutInstanceTest()
        {
            // TODO uncomment below to test "IsType" DocumentTypeOut
            //Assert.IsType<DocumentTypeOut>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'NumberPrefix'
        /// </summary>
        [Fact]
        public void NumberPrefixTest()
        {
            // TODO unit test for the property 'NumberPrefix'
        }

        /// <summary>
        /// Test the property 'Payable'
        /// </summary>
        [Fact]
        public void PayableTest()
        {
            // TODO unit test for the property 'Payable'
        }

        /// <summary>
        /// Test the property 'RequiresSourceDocument'
        /// </summary>
        [Fact]
        public void RequiresSourceDocumentTest()
        {
            // TODO unit test for the property 'RequiresSourceDocument'
        }

        /// <summary>
        /// Test the property 'SupportsReason'
        /// </summary>
        [Fact]
        public void SupportsReasonTest()
        {
            // TODO unit test for the property 'SupportsReason'
        }

        /// <summary>
        /// Test the property 'LineItemType'
        /// </summary>
        [Fact]
        public void LineItemTypeTest()
        {
            // TODO unit test for the property 'LineItemType'
        }

        /// <summary>
        /// Test the property 'Actions'
        /// </summary>
        [Fact]
        public void ActionsTest()
        {
            // TODO unit test for the property 'Actions'
        }
    }
}
