/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing ElectronicAddress
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ElectronicAddressTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ElectronicAddress
        //private ElectronicAddress instance;

        public ElectronicAddressTests()
        {
            // TODO uncomment below to create an instance of ElectronicAddress
            //instance = new ElectronicAddress();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ElectronicAddress
        /// </summary>
        [Fact]
        public void ElectronicAddressInstanceTest()
        {
            // TODO uncomment below to test "IsType" ElectronicAddress
            //Assert.IsType<ElectronicAddress>(instance);
        }

        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Fact]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }

        /// <summary>
        /// Test the property 'SchemeId'
        /// </summary>
        [Fact]
        public void SchemeIdTest()
        {
            // TODO unit test for the property 'SchemeId'
        }
    }
}
