/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing InvoiceTotalsOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class InvoiceTotalsOutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for InvoiceTotalsOut
        //private InvoiceTotalsOut instance;

        public InvoiceTotalsOutTests()
        {
            // TODO uncomment below to create an instance of InvoiceTotalsOut
            //instance = new InvoiceTotalsOut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of InvoiceTotalsOut
        /// </summary>
        [Fact]
        public void InvoiceTotalsOutInstanceTest()
        {
            // TODO uncomment below to test "IsType" InvoiceTotalsOut
            //Assert.IsType<InvoiceTotalsOut>(instance);
        }

        /// <summary>
        /// Test the property 'Subtotal'
        /// </summary>
        [Fact]
        public void SubtotalTest()
        {
            // TODO unit test for the property 'Subtotal'
        }

        /// <summary>
        /// Test the property 'DiscountTotal'
        /// </summary>
        [Fact]
        public void DiscountTotalTest()
        {
            // TODO unit test for the property 'DiscountTotal'
        }

        /// <summary>
        /// Test the property 'TaxTotal'
        /// </summary>
        [Fact]
        public void TaxTotalTest()
        {
            // TODO unit test for the property 'TaxTotal'
        }

        /// <summary>
        /// Test the property 'ShippingTotal'
        /// </summary>
        [Fact]
        public void ShippingTotalTest()
        {
            // TODO unit test for the property 'ShippingTotal'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
