/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing RenderComplianceOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RenderComplianceOutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RenderComplianceOut
        //private RenderComplianceOut instance;

        public RenderComplianceOutTests()
        {
            // TODO uncomment below to create an instance of RenderComplianceOut
            //instance = new RenderComplianceOut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RenderComplianceOut
        /// </summary>
        [Fact]
        public void RenderComplianceOutInstanceTest()
        {
            // TODO uncomment below to test "IsType" RenderComplianceOut
            //Assert.IsType<RenderComplianceOut>(instance);
        }

        /// <summary>
        /// Test the property 'Profile'
        /// </summary>
        [Fact]
        public void ProfileTest()
        {
            // TODO unit test for the property 'Profile'
        }

        /// <summary>
        /// Test the property 'RulesetVersion'
        /// </summary>
        [Fact]
        public void RulesetVersionTest()
        {
            // TODO unit test for the property 'RulesetVersion'
        }

        /// <summary>
        /// Test the property 'FullyChecked'
        /// </summary>
        [Fact]
        public void FullyCheckedTest()
        {
            // TODO unit test for the property 'FullyChecked'
        }

        /// <summary>
        /// Test the property 'Advisories'
        /// </summary>
        [Fact]
        public void AdvisoriesTest()
        {
            // TODO unit test for the property 'Advisories'
        }
    }
}
