/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateVersionCreateRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateVersionCreateRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateVersionCreateRequest
        //private TemplateVersionCreateRequest instance;

        public TemplateVersionCreateRequestTests()
        {
            // TODO uncomment below to create an instance of TemplateVersionCreateRequest
            //instance = new TemplateVersionCreateRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateVersionCreateRequest
        /// </summary>
        [Fact]
        public void TemplateVersionCreateRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateVersionCreateRequest
            //Assert.IsType<TemplateVersionCreateRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }

        /// <summary>
        /// Test the property 'Changelog'
        /// </summary>
        [Fact]
        public void ChangelogTest()
        {
            // TODO unit test for the property 'Changelog'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }
    }
}
