/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing TemplateDetail
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TemplateDetailTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TemplateDetail
        //private TemplateDetail instance;

        public TemplateDetailTests()
        {
            // TODO uncomment below to create an instance of TemplateDetail
            //instance = new TemplateDetail();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TemplateDetail
        /// </summary>
        [Fact]
        public void TemplateDetailInstanceTest()
        {
            // TODO uncomment below to test "IsType" TemplateDetail
            //Assert.IsType<TemplateDetail>(instance);
        }

        /// <summary>
        /// Test the property 'TemplateId'
        /// </summary>
        [Fact]
        public void TemplateIdTest()
        {
            // TODO unit test for the property 'TemplateId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DocumentType'
        /// </summary>
        [Fact]
        public void DocumentTypeTest()
        {
            // TODO unit test for the property 'DocumentType'
        }

        /// <summary>
        /// Test the property 'Engine'
        /// </summary>
        [Fact]
        public void EngineTest()
        {
            // TODO unit test for the property 'Engine'
        }
    }
}
