/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing UsageEventOut
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsageEventOutTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsageEventOut
        //private UsageEventOut instance;

        public UsageEventOutTests()
        {
            // TODO uncomment below to create an instance of UsageEventOut
            //instance = new UsageEventOut();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsageEventOut
        /// </summary>
        [Fact]
        public void UsageEventOutInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsageEventOut
            //Assert.IsType<UsageEventOut>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'RenderId'
        /// </summary>
        [Fact]
        public void RenderIdTest()
        {
            // TODO unit test for the property 'RenderId'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }
    }
}
