/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing UsageOverage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UsageOverageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UsageOverage
        //private UsageOverage instance;

        public UsageOverageTests()
        {
            // TODO uncomment below to create an instance of UsageOverage
            //instance = new UsageOverage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UsageOverage
        /// </summary>
        [Fact]
        public void UsageOverageInstanceTest()
        {
            // TODO uncomment below to test "IsType" UsageOverage
            //Assert.IsType<UsageOverage>(instance);
        }

        /// <summary>
        /// Test the property 'Enabled'
        /// </summary>
        [Fact]
        public void EnabledTest()
        {
            // TODO unit test for the property 'Enabled'
        }

        /// <summary>
        /// Test the property 'Available'
        /// </summary>
        [Fact]
        public void AvailableTest()
        {
            // TODO unit test for the property 'Available'
        }

        /// <summary>
        /// Test the property 'Renders'
        /// </summary>
        [Fact]
        public void RendersTest()
        {
            // TODO unit test for the property 'Renders'
        }

        /// <summary>
        /// Test the property 'PriceMillicents'
        /// </summary>
        [Fact]
        public void PriceMillicentsTest()
        {
            // TODO unit test for the property 'PriceMillicents'
        }

        /// <summary>
        /// Test the property 'EstimatedCostCents'
        /// </summary>
        [Fact]
        public void EstimatedCostCentsTest()
        {
            // TODO unit test for the property 'EstimatedCostCents'
        }
    }
}
