/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceMemberPatchRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkspaceMemberPatchRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkspaceMemberPatchRequest
        //private WorkspaceMemberPatchRequest instance;

        public WorkspaceMemberPatchRequestTests()
        {
            // TODO uncomment below to create an instance of WorkspaceMemberPatchRequest
            //instance = new WorkspaceMemberPatchRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceMemberPatchRequest
        /// </summary>
        [Fact]
        public void WorkspaceMemberPatchRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkspaceMemberPatchRequest
            //Assert.IsType<WorkspaceMemberPatchRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Role'
        /// </summary>
        [Fact]
        public void RoleTest()
        {
            // TODO unit test for the property 'Role'
        }
    }
}
