/*
 * InvoicePDFs
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using InvoicePDFs.Model;
using InvoicePDFs.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace InvoicePDFs.Test.Model
{
    /// <summary>
    ///  Class for testing WorkspaceResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WorkspaceResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WorkspaceResponse
        //private WorkspaceResponse instance;

        public WorkspaceResponseTests()
        {
            // TODO uncomment below to create an instance of WorkspaceResponse
            //instance = new WorkspaceResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WorkspaceResponse
        /// </summary>
        [Fact]
        public void WorkspaceResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" WorkspaceResponse
            //Assert.IsType<WorkspaceResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
