/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// AuthAccountData
    /// </summary>
    [DataContract(Name = "AuthAccountData")]
    public partial class AuthAccountData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthAccountData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected AuthAccountData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="AuthAccountData" /> class.
        /// </summary>
        /// <param name="accountId">accountId (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="email">email.</param>
        /// <param name="planId">planId (required).</param>
        /// <param name="planName">planName (required).</param>
        public AuthAccountData(string accountId = default(string), string name = default(string), string email = default(string), string planId = default(string), string planName = default(string))
        {
            // to ensure "accountId" is required (not null)
            if (accountId == null)
            {
                throw new ArgumentNullException("accountId is a required property for AuthAccountData and cannot be null");
            }
            this.AccountId = accountId;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for AuthAccountData and cannot be null");
            }
            this.Name = name;
            // to ensure "planId" is required (not null)
            if (planId == null)
            {
                throw new ArgumentNullException("planId is a required property for AuthAccountData and cannot be null");
            }
            this.PlanId = planId;
            // to ensure "planName" is required (not null)
            if (planName == null)
            {
                throw new ArgumentNullException("planName is a required property for AuthAccountData and cannot be null");
            }
            this.PlanName = planName;
            this.Email = email;
        }

        /// <summary>
        /// Gets or Sets AccountId
        /// </summary>
        [DataMember(Name = "account_id", IsRequired = true, EmitDefaultValue = true)]
        public string AccountId { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets PlanId
        /// </summary>
        [DataMember(Name = "plan_id", IsRequired = true, EmitDefaultValue = true)]
        public string PlanId { get; set; }

        /// <summary>
        /// Gets or Sets PlanName
        /// </summary>
        [DataMember(Name = "plan_name", IsRequired = true, EmitDefaultValue = true)]
        public string PlanName { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class AuthAccountData {\n");
            sb.Append("  AccountId: ").Append(AccountId).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  PlanId: ").Append(PlanId).Append("\n");
            sb.Append("  PlanName: ").Append(PlanName).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
