/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// BatchCreateRequest
    /// </summary>
    [DataContract(Name = "BatchCreateRequest")]
    public partial class BatchCreateRequest : IValidatableObject
    {
        /// <summary>
        /// Defines Operation
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum OperationEnum
        {
            /// <summary>
            /// Enum Render for value: render
            /// </summary>
            [EnumMember(Value = "render")]
            Render = 1
        }


        /// <summary>
        /// Gets or Sets Operation
        /// </summary>
        [DataMember(Name = "operation", EmitDefaultValue = false)]
        public OperationEnum? Operation { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchCreateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BatchCreateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BatchCreateRequest" /> class.
        /// </summary>
        /// <param name="operation">operation (default to OperationEnum.Render).</param>
        /// <param name="items">items (required).</param>
        /// <param name="templateId">templateId (default to &quot;tpl_modern&quot;).</param>
        /// <param name="output">output.</param>
        public BatchCreateRequest(OperationEnum? operation = OperationEnum.Render, List<BatchItemInput> items = default(List<BatchItemInput>), string templateId = @"tpl_modern", BatchOutputOptions output = default(BatchOutputOptions))
        {
            // to ensure "items" is required (not null)
            if (items == null)
            {
                throw new ArgumentNullException("items is a required property for BatchCreateRequest and cannot be null");
            }
            this.Items = items;
            this.Operation = operation;
            // use default value if no "templateId" provided
            this.TemplateId = templateId ?? @"tpl_modern";
            this.Output = output;
        }

        /// <summary>
        /// Gets or Sets Items
        /// </summary>
        [DataMember(Name = "items", IsRequired = true, EmitDefaultValue = true)]
        public List<BatchItemInput> Items { get; set; }

        /// <summary>
        /// Gets or Sets TemplateId
        /// </summary>
        [DataMember(Name = "template_id", EmitDefaultValue = false)]
        public string TemplateId { get; set; }

        /// <summary>
        /// Gets or Sets Output
        /// </summary>
        [DataMember(Name = "output", EmitDefaultValue = false)]
        public BatchOutputOptions Output { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BatchCreateRequest {\n");
            sb.Append("  Operation: ").Append(Operation).Append("\n");
            sb.Append("  Items: ").Append(Items).Append("\n");
            sb.Append("  TemplateId: ").Append(TemplateId).Append("\n");
            sb.Append("  Output: ").Append(Output).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
