/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// BillingCheckoutRequest
    /// </summary>
    [DataContract(Name = "BillingCheckoutRequest")]
    public partial class BillingCheckoutRequest : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingCheckoutRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BillingCheckoutRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingCheckoutRequest" /> class.
        /// </summary>
        /// <param name="priceId">Stripe price ID for the plan (required).</param>
        public BillingCheckoutRequest(string priceId = default(string))
        {
            // to ensure "priceId" is required (not null)
            if (priceId == null)
            {
                throw new ArgumentNullException("priceId is a required property for BillingCheckoutRequest and cannot be null");
            }
            this.PriceId = priceId;
        }

        /// <summary>
        /// Stripe price ID for the plan
        /// </summary>
        /// <value>Stripe price ID for the plan</value>
        [DataMember(Name = "price_id", IsRequired = true, EmitDefaultValue = true)]
        public string PriceId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingCheckoutRequest {\n");
            sb.Append("  PriceId: ").Append(PriceId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
