/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// BillingOverageData
    /// </summary>
    [DataContract(Name = "BillingOverageData")]
    public partial class BillingOverageData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingOverageData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BillingOverageData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingOverageData" /> class.
        /// </summary>
        /// <param name="overageEnabled">overageEnabled (required).</param>
        /// <param name="overageAvailable">overageAvailable (required).</param>
        /// <param name="overagePriceMillicents">overagePriceMillicents.</param>
        public BillingOverageData(bool overageEnabled = default(bool), bool overageAvailable = default(bool), int? overagePriceMillicents = default(int?))
        {
            this.OverageEnabled = overageEnabled;
            this.OverageAvailable = overageAvailable;
            this.OveragePriceMillicents = overagePriceMillicents;
        }

        /// <summary>
        /// Gets or Sets OverageEnabled
        /// </summary>
        [DataMember(Name = "overage_enabled", IsRequired = true, EmitDefaultValue = true)]
        public bool OverageEnabled { get; set; }

        /// <summary>
        /// Gets or Sets OverageAvailable
        /// </summary>
        [DataMember(Name = "overage_available", IsRequired = true, EmitDefaultValue = true)]
        public bool OverageAvailable { get; set; }

        /// <summary>
        /// Gets or Sets OveragePriceMillicents
        /// </summary>
        [DataMember(Name = "overage_price_millicents", EmitDefaultValue = true)]
        public int? OveragePriceMillicents { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingOverageData {\n");
            sb.Append("  OverageEnabled: ").Append(OverageEnabled).Append("\n");
            sb.Append("  OverageAvailable: ").Append(OverageAvailable).Append("\n");
            sb.Append("  OveragePriceMillicents: ").Append(OveragePriceMillicents).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
