/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// BillingPortalData
    /// </summary>
    [DataContract(Name = "BillingPortalData")]
    public partial class BillingPortalData : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingPortalData" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BillingPortalData() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BillingPortalData" /> class.
        /// </summary>
        /// <param name="url">url (required).</param>
        public BillingPortalData(string url = default(string))
        {
            // to ensure "url" is required (not null)
            if (url == null)
            {
                throw new ArgumentNullException("url is a required property for BillingPortalData and cannot be null");
            }
            this.Url = url;
        }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", IsRequired = true, EmitDefaultValue = true)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BillingPortalData {\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
