/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// BrandingOut
    /// </summary>
    [DataContract(Name = "BrandingOut")]
    public partial class BrandingOut : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BrandingOut" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BrandingOut() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BrandingOut" /> class.
        /// </summary>
        /// <param name="logoFileId">logoFileId.</param>
        /// <param name="primaryColor">primaryColor (required).</param>
        /// <param name="accentColor">accentColor (required).</param>
        /// <param name="fontFamily">fontFamily.</param>
        /// <param name="footerText">footerText (required).</param>
        /// <param name="hideInvoicepdfsBranding">hideInvoicepdfsBranding (required).</param>
        /// <param name="createdAt">createdAt (required).</param>
        /// <param name="updatedAt">updatedAt (required).</param>
        public BrandingOut(string logoFileId = default(string), string primaryColor = default(string), string accentColor = default(string), string fontFamily = default(string), string footerText = default(string), bool hideInvoicepdfsBranding = default(bool), string createdAt = default(string), string updatedAt = default(string))
        {
            // to ensure "primaryColor" is required (not null)
            if (primaryColor == null)
            {
                throw new ArgumentNullException("primaryColor is a required property for BrandingOut and cannot be null");
            }
            this.PrimaryColor = primaryColor;
            // to ensure "accentColor" is required (not null)
            if (accentColor == null)
            {
                throw new ArgumentNullException("accentColor is a required property for BrandingOut and cannot be null");
            }
            this.AccentColor = accentColor;
            // to ensure "footerText" is required (not null)
            if (footerText == null)
            {
                throw new ArgumentNullException("footerText is a required property for BrandingOut and cannot be null");
            }
            this.FooterText = footerText;
            this.HideInvoicepdfsBranding = hideInvoicepdfsBranding;
            // to ensure "createdAt" is required (not null)
            if (createdAt == null)
            {
                throw new ArgumentNullException("createdAt is a required property for BrandingOut and cannot be null");
            }
            this.CreatedAt = createdAt;
            // to ensure "updatedAt" is required (not null)
            if (updatedAt == null)
            {
                throw new ArgumentNullException("updatedAt is a required property for BrandingOut and cannot be null");
            }
            this.UpdatedAt = updatedAt;
            this.LogoFileId = logoFileId;
            this.FontFamily = fontFamily;
        }

        /// <summary>
        /// Gets or Sets LogoFileId
        /// </summary>
        [DataMember(Name = "logo_file_id", EmitDefaultValue = true)]
        public string LogoFileId { get; set; }

        /// <summary>
        /// Gets or Sets PrimaryColor
        /// </summary>
        [DataMember(Name = "primary_color", IsRequired = true, EmitDefaultValue = true)]
        public string PrimaryColor { get; set; }

        /// <summary>
        /// Gets or Sets AccentColor
        /// </summary>
        [DataMember(Name = "accent_color", IsRequired = true, EmitDefaultValue = true)]
        public string AccentColor { get; set; }

        /// <summary>
        /// Gets or Sets FontFamily
        /// </summary>
        [DataMember(Name = "font_family", EmitDefaultValue = true)]
        public string FontFamily { get; set; }

        /// <summary>
        /// Gets or Sets FooterText
        /// </summary>
        [DataMember(Name = "footer_text", IsRequired = true, EmitDefaultValue = true)]
        public string FooterText { get; set; }

        /// <summary>
        /// Gets or Sets HideInvoicepdfsBranding
        /// </summary>
        [DataMember(Name = "hide_invoicepdfs_branding", IsRequired = true, EmitDefaultValue = true)]
        public bool HideInvoicepdfsBranding { get; set; }

        /// <summary>
        /// Gets or Sets CreatedAt
        /// </summary>
        [DataMember(Name = "created_at", IsRequired = true, EmitDefaultValue = true)]
        public string CreatedAt { get; set; }

        /// <summary>
        /// Gets or Sets UpdatedAt
        /// </summary>
        [DataMember(Name = "updated_at", IsRequired = true, EmitDefaultValue = true)]
        public string UpdatedAt { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BrandingOut {\n");
            sb.Append("  LogoFileId: ").Append(LogoFileId).Append("\n");
            sb.Append("  PrimaryColor: ").Append(PrimaryColor).Append("\n");
            sb.Append("  AccentColor: ").Append(AccentColor).Append("\n");
            sb.Append("  FontFamily: ").Append(FontFamily).Append("\n");
            sb.Append("  FooterText: ").Append(FooterText).Append("\n");
            sb.Append("  HideInvoicepdfsBranding: ").Append(HideInvoicepdfsBranding).Append("\n");
            sb.Append("  CreatedAt: ").Append(CreatedAt).Append("\n");
            sb.Append("  UpdatedAt: ").Append(UpdatedAt).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
