/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// BusinessProfileCreate
    /// </summary>
    [DataContract(Name = "BusinessProfileCreate")]
    public partial class BusinessProfileCreate : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessProfileCreate" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BusinessProfileCreate() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BusinessProfileCreate" /> class.
        /// </summary>
        /// <param name="legalName">legalName (required).</param>
        /// <param name="displayName">displayName.</param>
        /// <param name="email">email.</param>
        /// <param name="phone">phone.</param>
        /// <param name="website">website.</param>
        /// <param name="taxId">taxId.</param>
        /// <param name="address">address.</param>
        /// <param name="defaultCurrency">defaultCurrency.</param>
        /// <param name="defaultLocale">defaultLocale.</param>
        /// <param name="defaultTimezone">defaultTimezone.</param>
        /// <param name="logoFileId">logoFileId.</param>
        public BusinessProfileCreate(string legalName = default(string), string displayName = default(string), string email = default(string), string phone = default(string), string website = default(string), string taxId = default(string), PostalAddress address = default(PostalAddress), string defaultCurrency = default(string), string defaultLocale = default(string), string defaultTimezone = default(string), string logoFileId = default(string))
        {
            // to ensure "legalName" is required (not null)
            if (legalName == null)
            {
                throw new ArgumentNullException("legalName is a required property for BusinessProfileCreate and cannot be null");
            }
            this.LegalName = legalName;
            this.DisplayName = displayName;
            this.Email = email;
            this.Phone = phone;
            this.Website = website;
            this.TaxId = taxId;
            this.Address = address;
            this.DefaultCurrency = defaultCurrency;
            this.DefaultLocale = defaultLocale;
            this.DefaultTimezone = defaultTimezone;
            this.LogoFileId = logoFileId;
        }

        /// <summary>
        /// Gets or Sets LegalName
        /// </summary>
        /// <example>Acme Corp Inc.</example>
        [DataMember(Name = "legal_name", IsRequired = true, EmitDefaultValue = true)]
        public string LegalName { get; set; }

        /// <summary>
        /// Gets or Sets DisplayName
        /// </summary>
        [DataMember(Name = "display_name", EmitDefaultValue = true)]
        public string DisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name = "email", EmitDefaultValue = true)]
        public string Email { get; set; }

        /// <summary>
        /// Gets or Sets Phone
        /// </summary>
        [DataMember(Name = "phone", EmitDefaultValue = true)]
        public string Phone { get; set; }

        /// <summary>
        /// Gets or Sets Website
        /// </summary>
        [DataMember(Name = "website", EmitDefaultValue = true)]
        public string Website { get; set; }

        /// <summary>
        /// Gets or Sets TaxId
        /// </summary>
        [DataMember(Name = "tax_id", EmitDefaultValue = true)]
        public string TaxId { get; set; }

        /// <summary>
        /// Gets or Sets Address
        /// </summary>
        [DataMember(Name = "address", EmitDefaultValue = true)]
        public PostalAddress Address { get; set; }

        /// <summary>
        /// Gets or Sets DefaultCurrency
        /// </summary>
        [DataMember(Name = "default_currency", EmitDefaultValue = true)]
        public string DefaultCurrency { get; set; }

        /// <summary>
        /// Gets or Sets DefaultLocale
        /// </summary>
        [DataMember(Name = "default_locale", EmitDefaultValue = true)]
        public string DefaultLocale { get; set; }

        /// <summary>
        /// Gets or Sets DefaultTimezone
        /// </summary>
        [DataMember(Name = "default_timezone", EmitDefaultValue = true)]
        public string DefaultTimezone { get; set; }

        /// <summary>
        /// Gets or Sets LogoFileId
        /// </summary>
        [DataMember(Name = "logo_file_id", EmitDefaultValue = true)]
        public string LogoFileId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class BusinessProfileCreate {\n");
            sb.Append("  LegalName: ").Append(LegalName).Append("\n");
            sb.Append("  DisplayName: ").Append(DisplayName).Append("\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Phone: ").Append(Phone).Append("\n");
            sb.Append("  Website: ").Append(Website).Append("\n");
            sb.Append("  TaxId: ").Append(TaxId).Append("\n");
            sb.Append("  Address: ").Append(Address).Append("\n");
            sb.Append("  DefaultCurrency: ").Append(DefaultCurrency).Append("\n");
            sb.Append("  DefaultLocale: ").Append(DefaultLocale).Append("\n");
            sb.Append("  DefaultTimezone: ").Append(DefaultTimezone).Append("\n");
            sb.Append("  LogoFileId: ").Append(LogoFileId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
