/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.1.2
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// DocumentPatchRequest
    /// </summary>
    [DataContract(Name = "DocumentPatchRequest")]
    public partial class DocumentPatchRequest : IValidatableObject
    {
        /// <summary>
        /// Defines DocumentType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DocumentTypeEnum
        {
            /// <summary>
            /// Enum Invoice for value: invoice
            /// </summary>
            [EnumMember(Value = "invoice")]
            Invoice = 1,

            /// <summary>
            /// Enum CreditNote for value: credit_note
            /// </summary>
            [EnumMember(Value = "credit_note")]
            CreditNote = 2,

            /// <summary>
            /// Enum Quote for value: quote
            /// </summary>
            [EnumMember(Value = "quote")]
            Quote = 3,

            /// <summary>
            /// Enum Receipt for value: receipt
            /// </summary>
            [EnumMember(Value = "receipt")]
            Receipt = 4,

            /// <summary>
            /// Enum Proforma for value: proforma
            /// </summary>
            [EnumMember(Value = "proforma")]
            Proforma = 5,

            /// <summary>
            /// Enum PurchaseOrder for value: purchase_order
            /// </summary>
            [EnumMember(Value = "purchase_order")]
            PurchaseOrder = 6,

            /// <summary>
            /// Enum DeliveryNote for value: delivery_note
            /// </summary>
            [EnumMember(Value = "delivery_note")]
            DeliveryNote = 7
        }


        /// <summary>
        /// Gets or Sets DocumentType
        /// </summary>
        [DataMember(Name = "document_type", EmitDefaultValue = true)]
        public DocumentTypeEnum? DocumentType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentPatchRequest" /> class.
        /// </summary>
        /// <param name="number">number.</param>
        /// <param name="documentType">documentType.</param>
        /// <param name="issueDate">issueDate.</param>
        /// <param name="dueDate">dueDate.</param>
        /// <param name="currency">currency.</param>
        /// <param name="locale">locale.</param>
        /// <param name="businessProfileId">businessProfileId.</param>
        /// <param name="customerId">customerId.</param>
        /// <param name="sourceDocumentId">sourceDocumentId.</param>
        /// <param name="reason">reason.</param>
        /// <param name="shipTo">shipTo.</param>
        /// <param name="lineItems">lineItems.</param>
        /// <param name="discounts">discounts.</param>
        /// <param name="shipping">shipping.</param>
        /// <param name="notes">notes.</param>
        /// <param name="terms">terms.</param>
        /// <param name="customFields">customFields.</param>
        /// <param name="payment">payment.</param>
        /// <param name="branding">branding.</param>
        public DocumentPatchRequest(string number = default(string), DocumentTypeEnum? documentType = default(DocumentTypeEnum?), DateOnly issueDate = default(DateOnly), DateOnly dueDate = default(DateOnly), string currency = default(string), string locale = default(string), string businessProfileId = default(string), string customerId = default(string), string sourceDocumentId = default(string), string reason = default(string), PostalAddress shipTo = default(PostalAddress), List<StandardLineItemInput> lineItems = default(List<StandardLineItemInput>), List<LineItemDiscountInput> discounts = default(List<LineItemDiscountInput>), InvoiceShippingInput shipping = default(InvoiceShippingInput), List<InvoiceNoteInput> notes = default(List<InvoiceNoteInput>), List<InvoiceTermInput> terms = default(List<InvoiceTermInput>), List<InvoiceCustomFieldInput> customFields = default(List<InvoiceCustomFieldInput>), InvoicePaymentInput payment = default(InvoicePaymentInput), InvoiceBrandingInput branding = default(InvoiceBrandingInput))
        {
            this.Number = number;
            this.DocumentType = documentType;
            this.IssueDate = issueDate;
            this.DueDate = dueDate;
            this.Currency = currency;
            this.Locale = locale;
            this.BusinessProfileId = businessProfileId;
            this.CustomerId = customerId;
            this.SourceDocumentId = sourceDocumentId;
            this.Reason = reason;
            this.ShipTo = shipTo;
            this.LineItems = lineItems;
            this.Discounts = discounts;
            this.Shipping = shipping;
            this.Notes = notes;
            this.Terms = terms;
            this.CustomFields = customFields;
            this.Payment = payment;
            this.Branding = branding;
        }

        /// <summary>
        /// Gets or Sets Number
        /// </summary>
        [DataMember(Name = "number", EmitDefaultValue = true)]
        public string Number { get; set; }

        /// <summary>
        /// Gets or Sets IssueDate
        /// </summary>
        [DataMember(Name = "issue_date", EmitDefaultValue = true)]
        public DateOnly IssueDate { get; set; }

        /// <summary>
        /// Gets or Sets DueDate
        /// </summary>
        [DataMember(Name = "due_date", EmitDefaultValue = true)]
        public DateOnly DueDate { get; set; }

        /// <summary>
        /// Gets or Sets Currency
        /// </summary>
        [DataMember(Name = "currency", EmitDefaultValue = true)]
        public string Currency { get; set; }

        /// <summary>
        /// Gets or Sets Locale
        /// </summary>
        [DataMember(Name = "locale", EmitDefaultValue = true)]
        public string Locale { get; set; }

        /// <summary>
        /// Gets or Sets BusinessProfileId
        /// </summary>
        [DataMember(Name = "business_profile_id", EmitDefaultValue = true)]
        public string BusinessProfileId { get; set; }

        /// <summary>
        /// Gets or Sets CustomerId
        /// </summary>
        [DataMember(Name = "customer_id", EmitDefaultValue = true)]
        public string CustomerId { get; set; }

        /// <summary>
        /// Gets or Sets SourceDocumentId
        /// </summary>
        [DataMember(Name = "source_document_id", EmitDefaultValue = true)]
        public string SourceDocumentId { get; set; }

        /// <summary>
        /// Gets or Sets Reason
        /// </summary>
        [DataMember(Name = "reason", EmitDefaultValue = true)]
        public string Reason { get; set; }

        /// <summary>
        /// Gets or Sets ShipTo
        /// </summary>
        [DataMember(Name = "ship_to", EmitDefaultValue = true)]
        public PostalAddress ShipTo { get; set; }

        /// <summary>
        /// Gets or Sets LineItems
        /// </summary>
        [DataMember(Name = "line_items", EmitDefaultValue = true)]
        public List<StandardLineItemInput> LineItems { get; set; }

        /// <summary>
        /// Gets or Sets Discounts
        /// </summary>
        [DataMember(Name = "discounts", EmitDefaultValue = true)]
        public List<LineItemDiscountInput> Discounts { get; set; }

        /// <summary>
        /// Gets or Sets Shipping
        /// </summary>
        [DataMember(Name = "shipping", EmitDefaultValue = true)]
        public InvoiceShippingInput Shipping { get; set; }

        /// <summary>
        /// Gets or Sets Notes
        /// </summary>
        [DataMember(Name = "notes", EmitDefaultValue = true)]
        public List<InvoiceNoteInput> Notes { get; set; }

        /// <summary>
        /// Gets or Sets Terms
        /// </summary>
        [DataMember(Name = "terms", EmitDefaultValue = true)]
        public List<InvoiceTermInput> Terms { get; set; }

        /// <summary>
        /// Gets or Sets CustomFields
        /// </summary>
        [DataMember(Name = "custom_fields", EmitDefaultValue = true)]
        public List<InvoiceCustomFieldInput> CustomFields { get; set; }

        /// <summary>
        /// Gets or Sets Payment
        /// </summary>
        [DataMember(Name = "payment", EmitDefaultValue = true)]
        public InvoicePaymentInput Payment { get; set; }

        /// <summary>
        /// Gets or Sets Branding
        /// </summary>
        [DataMember(Name = "branding", EmitDefaultValue = true)]
        public InvoiceBrandingInput Branding { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentPatchRequest {\n");
            sb.Append("  Number: ").Append(Number).Append("\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  IssueDate: ").Append(IssueDate).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  Currency: ").Append(Currency).Append("\n");
            sb.Append("  Locale: ").Append(Locale).Append("\n");
            sb.Append("  BusinessProfileId: ").Append(BusinessProfileId).Append("\n");
            sb.Append("  CustomerId: ").Append(CustomerId).Append("\n");
            sb.Append("  SourceDocumentId: ").Append(SourceDocumentId).Append("\n");
            sb.Append("  Reason: ").Append(Reason).Append("\n");
            sb.Append("  ShipTo: ").Append(ShipTo).Append("\n");
            sb.Append("  LineItems: ").Append(LineItems).Append("\n");
            sb.Append("  Discounts: ").Append(Discounts).Append("\n");
            sb.Append("  Shipping: ").Append(Shipping).Append("\n");
            sb.Append("  Notes: ").Append(Notes).Append("\n");
            sb.Append("  Terms: ").Append(Terms).Append("\n");
            sb.Append("  CustomFields: ").Append(CustomFields).Append("\n");
            sb.Append("  Payment: ").Append(Payment).Append("\n");
            sb.Append("  Branding: ").Append(Branding).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Currency (string) maxLength
            if (this.Currency != null && this.Currency.Length > 3)
            {
                yield return new ValidationResult("Invalid value for Currency, length must be less than 3.", new [] { "Currency" });
            }

            // Currency (string) minLength
            if (this.Currency != null && this.Currency.Length < 3)
            {
                yield return new ValidationResult("Invalid value for Currency, length must be greater than 3.", new [] { "Currency" });
            }

            yield break;
        }
    }

}
