/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// DocumentComplianceRequest
    /// </summary>
    [DataContract(Name = "DocumentComplianceRequest")]
    public partial class DocumentComplianceRequest : IValidatableObject
    {
        /// <summary>
        /// Defines DocumentType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum DocumentTypeEnum
        {
            /// <summary>
            /// Enum Invoice for value: invoice
            /// </summary>
            [EnumMember(Value = "invoice")]
            Invoice = 1,

            /// <summary>
            /// Enum CreditNote for value: credit_note
            /// </summary>
            [EnumMember(Value = "credit_note")]
            CreditNote = 2,

            /// <summary>
            /// Enum Quote for value: quote
            /// </summary>
            [EnumMember(Value = "quote")]
            Quote = 3,

            /// <summary>
            /// Enum Receipt for value: receipt
            /// </summary>
            [EnumMember(Value = "receipt")]
            Receipt = 4,

            /// <summary>
            /// Enum Proforma for value: proforma
            /// </summary>
            [EnumMember(Value = "proforma")]
            Proforma = 5,

            /// <summary>
            /// Enum PurchaseOrder for value: purchase_order
            /// </summary>
            [EnumMember(Value = "purchase_order")]
            PurchaseOrder = 6,

            /// <summary>
            /// Enum DeliveryNote for value: delivery_note
            /// </summary>
            [EnumMember(Value = "delivery_note")]
            DeliveryNote = 7
        }


        /// <summary>
        /// Gets or Sets DocumentType
        /// </summary>
        [DataMember(Name = "document_type", EmitDefaultValue = false)]
        public DocumentTypeEnum? DocumentType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentComplianceRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DocumentComplianceRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentComplianceRequest" /> class.
        /// </summary>
        /// <param name="documentType">documentType (default to DocumentTypeEnum.Invoice).</param>
        /// <param name="data">data (required).</param>
        /// <param name="profile">Which ruleset to hold the document to. Rulesets differ: a document valid under one can be rejected by another, so there is no default. (required).</param>
        public DocumentComplianceRequest(DocumentTypeEnum? documentType = DocumentTypeEnum.Invoice, DocumentInvoiceDataInput data = default(DocumentInvoiceDataInput), string profile = default(string))
        {
            // to ensure "data" is required (not null)
            if (data == null)
            {
                throw new ArgumentNullException("data is a required property for DocumentComplianceRequest and cannot be null");
            }
            this.Data = data;
            // to ensure "profile" is required (not null)
            if (profile == null)
            {
                throw new ArgumentNullException("profile is a required property for DocumentComplianceRequest and cannot be null");
            }
            this.Profile = profile;
            this.DocumentType = documentType;
        }

        /// <summary>
        /// Gets or Sets Data
        /// </summary>
        [DataMember(Name = "data", IsRequired = true, EmitDefaultValue = true)]
        public DocumentInvoiceDataInput Data { get; set; }

        /// <summary>
        /// Which ruleset to hold the document to. Rulesets differ: a document valid under one can be rejected by another, so there is no default.
        /// </summary>
        /// <value>Which ruleset to hold the document to. Rulesets differ: a document valid under one can be rejected by another, so there is no default.</value>
        /// <example>peppol_bis_billing_3</example>
        [DataMember(Name = "profile", IsRequired = true, EmitDefaultValue = true)]
        public string Profile { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentComplianceRequest {\n");
            sb.Append("  DocumentType: ").Append(DocumentType).Append("\n");
            sb.Append("  Data: ").Append(Data).Append("\n");
            sb.Append("  Profile: ").Append(Profile).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
