/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// DocumentTypeOut
    /// </summary>
    [DataContract(Name = "DocumentTypeOut")]
    public partial class DocumentTypeOut : IValidatableObject
    {
        /// <summary>
        /// Defines LineItemType
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum LineItemTypeEnum
        {
            /// <summary>
            /// Enum Standard for value: standard
            /// </summary>
            [EnumMember(Value = "standard")]
            Standard = 1,

            /// <summary>
            /// Enum Shipped for value: shipped
            /// </summary>
            [EnumMember(Value = "shipped")]
            Shipped = 2
        }


        /// <summary>
        /// Gets or Sets LineItemType
        /// </summary>
        [DataMember(Name = "line_item_type", IsRequired = true, EmitDefaultValue = true)]
        public LineItemTypeEnum LineItemType { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentTypeOut" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected DocumentTypeOut() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="DocumentTypeOut" /> class.
        /// </summary>
        /// <param name="id">id (required).</param>
        /// <param name="name">name (required).</param>
        /// <param name="numberPrefix">numberPrefix (required).</param>
        /// <param name="payable">payable (required).</param>
        /// <param name="requiresSourceDocument">requiresSourceDocument (required).</param>
        /// <param name="supportsReason">supportsReason (required).</param>
        /// <param name="lineItemType">lineItemType (required).</param>
        /// <param name="actions">actions (required).</param>
        public DocumentTypeOut(string id = default(string), string name = default(string), string numberPrefix = default(string), bool payable = default(bool), bool requiresSourceDocument = default(bool), bool supportsReason = default(bool), LineItemTypeEnum lineItemType = default(LineItemTypeEnum), List<string> actions = default(List<string>))
        {
            // to ensure "id" is required (not null)
            if (id == null)
            {
                throw new ArgumentNullException("id is a required property for DocumentTypeOut and cannot be null");
            }
            this.Id = id;
            // to ensure "name" is required (not null)
            if (name == null)
            {
                throw new ArgumentNullException("name is a required property for DocumentTypeOut and cannot be null");
            }
            this.Name = name;
            // to ensure "numberPrefix" is required (not null)
            if (numberPrefix == null)
            {
                throw new ArgumentNullException("numberPrefix is a required property for DocumentTypeOut and cannot be null");
            }
            this.NumberPrefix = numberPrefix;
            this.Payable = payable;
            this.RequiresSourceDocument = requiresSourceDocument;
            this.SupportsReason = supportsReason;
            this.LineItemType = lineItemType;
            // to ensure "actions" is required (not null)
            if (actions == null)
            {
                throw new ArgumentNullException("actions is a required property for DocumentTypeOut and cannot be null");
            }
            this.Actions = actions;
        }

        /// <summary>
        /// Gets or Sets Id
        /// </summary>
        [DataMember(Name = "id", IsRequired = true, EmitDefaultValue = true)]
        public string Id { get; set; }

        /// <summary>
        /// Gets or Sets Name
        /// </summary>
        [DataMember(Name = "name", IsRequired = true, EmitDefaultValue = true)]
        public string Name { get; set; }

        /// <summary>
        /// Gets or Sets NumberPrefix
        /// </summary>
        [DataMember(Name = "number_prefix", IsRequired = true, EmitDefaultValue = true)]
        public string NumberPrefix { get; set; }

        /// <summary>
        /// Gets or Sets Payable
        /// </summary>
        [DataMember(Name = "payable", IsRequired = true, EmitDefaultValue = true)]
        public bool Payable { get; set; }

        /// <summary>
        /// Gets or Sets RequiresSourceDocument
        /// </summary>
        [DataMember(Name = "requires_source_document", IsRequired = true, EmitDefaultValue = true)]
        public bool RequiresSourceDocument { get; set; }

        /// <summary>
        /// Gets or Sets SupportsReason
        /// </summary>
        [DataMember(Name = "supports_reason", IsRequired = true, EmitDefaultValue = true)]
        public bool SupportsReason { get; set; }

        /// <summary>
        /// Gets or Sets Actions
        /// </summary>
        [DataMember(Name = "actions", IsRequired = true, EmitDefaultValue = true)]
        public List<string> Actions { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class DocumentTypeOut {\n");
            sb.Append("  Id: ").Append(Id).Append("\n");
            sb.Append("  Name: ").Append(Name).Append("\n");
            sb.Append("  NumberPrefix: ").Append(NumberPrefix).Append("\n");
            sb.Append("  Payable: ").Append(Payable).Append("\n");
            sb.Append("  RequiresSourceDocument: ").Append(RequiresSourceDocument).Append("\n");
            sb.Append("  SupportsReason: ").Append(SupportsReason).Append("\n");
            sb.Append("  LineItemType: ").Append(LineItemType).Append("\n");
            sb.Append("  Actions: ").Append(Actions).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
