/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = InvoicePDFs.Client.OpenAPIDateConverter;

namespace InvoicePDFs.Model
{
    /// <summary>
    /// What a custom template is: a built-in design plus the brand to render it in.  A custom template is not a design of its own — it names one of the built-ins in &#x60;&#x60;base_template_id&#x60;&#x60; and carries the values below, which are the same ones &#x60;&#x60;data.branding&#x60;&#x60; carries. They are applied *underneath* a request&#39;s own branding, so a document that states a colour still wins and one template can serve several brands.  Typed rather than the free-form object it used to be: nothing read that object, so every key in it was equally correct and a caller could keep sending &#x60;&#x60;primary_colour&#x60;&#x60; forever without a word back. Unset here means \&quot;the template has no opinion\&quot; — unlike &#x60;&#x60;Branding&#x60;&#x60;, whose every field has a non-empty default and so cannot say that.
    /// </summary>
    [DataContract(Name = "TemplateConfig")]
    public partial class TemplateConfig : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TemplateConfig" /> class.
        /// </summary>
        /// <param name="primaryColor">primaryColor.</param>
        /// <param name="accentColor">accentColor.</param>
        /// <param name="fontFamily">fontFamily.</param>
        /// <param name="headerText">headerText.</param>
        /// <param name="footerText">footerText.</param>
        public TemplateConfig(string primaryColor = default(string), string accentColor = default(string), string fontFamily = default(string), string headerText = default(string), string footerText = default(string))
        {
            this.PrimaryColor = primaryColor;
            this.AccentColor = accentColor;
            this.FontFamily = fontFamily;
            this.HeaderText = headerText;
            this.FooterText = footerText;
        }

        /// <summary>
        /// Gets or Sets PrimaryColor
        /// </summary>
        [DataMember(Name = "primary_color", EmitDefaultValue = true)]
        public string PrimaryColor { get; set; }

        /// <summary>
        /// Gets or Sets AccentColor
        /// </summary>
        [DataMember(Name = "accent_color", EmitDefaultValue = true)]
        public string AccentColor { get; set; }

        /// <summary>
        /// Gets or Sets FontFamily
        /// </summary>
        [DataMember(Name = "font_family", EmitDefaultValue = true)]
        public string FontFamily { get; set; }

        /// <summary>
        /// Gets or Sets HeaderText
        /// </summary>
        [DataMember(Name = "header_text", EmitDefaultValue = true)]
        public string HeaderText { get; set; }

        /// <summary>
        /// Gets or Sets FooterText
        /// </summary>
        [DataMember(Name = "footer_text", EmitDefaultValue = true)]
        public string FooterText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class TemplateConfig {\n");
            sb.Append("  PrimaryColor: ").Append(PrimaryColor).Append("\n");
            sb.Append("  AccentColor: ").Append(AccentColor).Append("\n");
            sb.Append("  FontFamily: ").Append(FontFamily).Append("\n");
            sb.Append("  HeaderText: ").Append(HeaderText).Append("\n");
            sb.Append("  FooterText: ").Append(FooterText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            if (this.PrimaryColor != null) {
                // PrimaryColor (string) pattern
                Regex regexPrimaryColor = new Regex(@"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$", RegexOptions.CultureInvariant);
                if (!regexPrimaryColor.Match(this.PrimaryColor).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PrimaryColor, must match a pattern of " + regexPrimaryColor, new [] { "PrimaryColor" });
                }
            }

            if (this.AccentColor != null) {
                // AccentColor (string) pattern
                Regex regexAccentColor = new Regex(@"^#(?:[0-9a-fA-F]{3}|[0-9a-fA-F]{6})$", RegexOptions.CultureInvariant);
                if (!regexAccentColor.Match(this.AccentColor).Success)
                {
                    yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for AccentColor, must match a pattern of " + regexAccentColor, new [] { "AccentColor" });
                }
            }

            yield break;
        }
    }

}
