/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using InvoicePDFs.Client;
using InvoicePDFs.Model;

namespace InvoicePDFs.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuditLogApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Get Audit Event
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuditEventResponse</returns>
        AuditEventResponse GetAuditEvent(string auditEventId, int operationIndex = 0);

        /// <summary>
        /// Get Audit Event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuditEventResponse</returns>
        ApiResponse<AuditEventResponse> GetAuditEventWithHttpInfo(string auditEventId, int operationIndex = 0);
        /// <summary>
        /// List Audit Events
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuditEventsListResponse</returns>
        AuditEventsListResponse ListAuditEvents(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0);

        /// <summary>
        /// List Audit Events
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuditEventsListResponse</returns>
        ApiResponse<AuditEventsListResponse> ListAuditEventsWithHttpInfo(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuditLogApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Get Audit Event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuditEventResponse</returns>
        System.Threading.Tasks.Task<AuditEventResponse> GetAuditEventAsync(string auditEventId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Audit Event
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuditEventResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuditEventResponse>> GetAuditEventWithHttpInfoAsync(string auditEventId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Audit Events
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuditEventsListResponse</returns>
        System.Threading.Tasks.Task<AuditEventsListResponse> ListAuditEventsAsync(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Audit Events
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuditEventsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<AuditEventsListResponse>> ListAuditEventsWithHttpInfoAsync(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IAuditLogApi : IAuditLogApiSync, IAuditLogApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class AuditLogApi : IAuditLogApi
    {
        private InvoicePDFs.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuditLogApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogApi"/> class.
        /// </summary>
        /// <returns></returns>
        public AuditLogApi(string basePath)
        {
            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                new InvoicePDFs.Client.Configuration { BasePath = basePath }
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public AuditLogApi(InvoicePDFs.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="AuditLogApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public AuditLogApi(InvoicePDFs.Client.ISynchronousClient client, InvoicePDFs.Client.IAsynchronousClient asyncClient, InvoicePDFs.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public InvoicePDFs.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public InvoicePDFs.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public InvoicePDFs.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public InvoicePDFs.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Get Audit Event 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuditEventResponse</returns>
        public AuditEventResponse GetAuditEvent(string auditEventId, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<AuditEventResponse> localVarResponse = GetAuditEventWithHttpInfo(auditEventId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Audit Event 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuditEventResponse</returns>
        public InvoicePDFs.Client.ApiResponse<AuditEventResponse> GetAuditEventWithHttpInfo(string auditEventId, int operationIndex = 0)
        {
            // verify the required parameter 'auditEventId' is set
            if (auditEventId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'auditEventId' when calling AuditLogApi->GetAuditEvent");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("audit_event_id", InvoicePDFs.Client.ClientUtils.ParameterToString(auditEventId)); // path parameter

            localVarRequestOptions.Operation = "AuditLogApi.GetAuditEvent";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AuditEventResponse>("/api/v1/audit-events/{audit_event_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAuditEvent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Audit Event 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuditEventResponse</returns>
        public async System.Threading.Tasks.Task<AuditEventResponse> GetAuditEventAsync(string auditEventId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<AuditEventResponse> localVarResponse = await GetAuditEventWithHttpInfoAsync(auditEventId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Audit Event 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="auditEventId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuditEventResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<AuditEventResponse>> GetAuditEventWithHttpInfoAsync(string auditEventId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'auditEventId' is set
            if (auditEventId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'auditEventId' when calling AuditLogApi->GetAuditEvent");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("audit_event_id", InvoicePDFs.Client.ClientUtils.ParameterToString(auditEventId)); // path parameter

            localVarRequestOptions.Operation = "AuditLogApi.GetAuditEvent";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<AuditEventResponse>("/api/v1/audit-events/{audit_event_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetAuditEvent", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Audit Events 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>AuditEventsListResponse</returns>
        public AuditEventsListResponse ListAuditEvents(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<AuditEventsListResponse> localVarResponse = ListAuditEventsWithHttpInfo(limit, cursor, action, resourceType, resourceId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Audit Events 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of AuditEventsListResponse</returns>
        public InvoicePDFs.Client.ApiResponse<AuditEventsListResponse> ListAuditEventsWithHttpInfo(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (action != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "action", action));
            }
            if (resourceType != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "resource_type", resourceType));
            }
            if (resourceId != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "resource_id", resourceId));
            }

            localVarRequestOptions.Operation = "AuditLogApi.ListAuditEvents";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<AuditEventsListResponse>("/api/v1/audit-events", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAuditEvents", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Audit Events 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of AuditEventsListResponse</returns>
        public async System.Threading.Tasks.Task<AuditEventsListResponse> ListAuditEventsAsync(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<AuditEventsListResponse> localVarResponse = await ListAuditEventsWithHttpInfoAsync(limit, cursor, action, resourceType, resourceId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Audit Events 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="action"> (optional)</param>
        /// <param name="resourceType"> (optional)</param>
        /// <param name="resourceId"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (AuditEventsListResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<AuditEventsListResponse>> ListAuditEventsWithHttpInfoAsync(int? limit = default(int?), string? cursor = default(string?), string? action = default(string?), string? resourceType = default(string?), string? resourceId = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }
            if (action != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "action", action));
            }
            if (resourceType != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "resource_type", resourceType));
            }
            if (resourceId != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "resource_id", resourceId));
            }

            localVarRequestOptions.Operation = "AuditLogApi.ListAuditEvents";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<AuditEventsListResponse>("/api/v1/audit-events", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListAuditEvents", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
