/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.2.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using InvoicePDFs.Client;
using InvoicePDFs.Model;

namespace InvoicePDFs.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Cancel Batch
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponse</returns>
        BatchResponse CancelBatch(string batchId, int operationIndex = 0);

        /// <summary>
        /// Cancel Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponse</returns>
        ApiResponse<BatchResponse> CancelBatchWithHttpInfo(string batchId, int operationIndex = 0);
        /// <summary>
        /// Create Batch
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponse</returns>
        BatchResponse CreateBatch(BatchCreateRequest batchCreateRequest, int operationIndex = 0);

        /// <summary>
        /// Create Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponse</returns>
        ApiResponse<BatchResponse> CreateBatchWithHttpInfo(BatchCreateRequest batchCreateRequest, int operationIndex = 0);
        /// <summary>
        /// Download Batch
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>System.IO.Stream</returns>
        System.IO.Stream DownloadBatch(string batchId, int operationIndex = 0);

        /// <summary>
        /// Download Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        ApiResponse<System.IO.Stream> DownloadBatchWithHttpInfo(string batchId, int operationIndex = 0);
        /// <summary>
        /// Get Batch
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponse</returns>
        BatchResponse GetBatch(string batchId, int operationIndex = 0);

        /// <summary>
        /// Get Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponse</returns>
        ApiResponse<BatchResponse> GetBatchWithHttpInfo(string batchId, int operationIndex = 0);
        /// <summary>
        /// List Batch Items
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchItemsListResponse</returns>
        BatchItemsListResponse ListBatchItems(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0);

        /// <summary>
        /// List Batch Items
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchItemsListResponse</returns>
        ApiResponse<BatchItemsListResponse> ListBatchItemsWithHttpInfo(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0);
        /// <summary>
        /// List Batches
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchesListResponse</returns>
        BatchesListResponse ListBatches(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0);

        /// <summary>
        /// List Batches
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchesListResponse</returns>
        ApiResponse<BatchesListResponse> ListBatchesWithHttpInfo(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Cancel Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponse</returns>
        System.Threading.Tasks.Task<BatchResponse> CancelBatchAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Cancel Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchResponse>> CancelBatchWithHttpInfoAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponse</returns>
        System.Threading.Tasks.Task<BatchResponse> CreateBatchAsync(BatchCreateRequest batchCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchResponse>> CreateBatchWithHttpInfoAsync(BatchCreateRequest batchCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Download Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        System.Threading.Tasks.Task<System.IO.Stream> DownloadBatchAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Download Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        System.Threading.Tasks.Task<ApiResponse<System.IO.Stream>> DownloadBatchWithHttpInfoAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponse</returns>
        System.Threading.Tasks.Task<BatchResponse> GetBatchAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Batch
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchResponse>> GetBatchWithHttpInfoAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Batch Items
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchItemsListResponse</returns>
        System.Threading.Tasks.Task<BatchItemsListResponse> ListBatchItemsAsync(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Batch Items
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchItemsListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchItemsListResponse>> ListBatchItemsWithHttpInfoAsync(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Batches
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchesListResponse</returns>
        System.Threading.Tasks.Task<BatchesListResponse> ListBatchesAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Batches
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchesListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BatchesListResponse>> ListBatchesWithHttpInfoAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBatchesApi : IBatchesApiSync, IBatchesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BatchesApi : IBatchesApi
    {
        private InvoicePDFs.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BatchesApi(string basePath)
        {
            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                new InvoicePDFs.Client.Configuration { BasePath = basePath }
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BatchesApi(InvoicePDFs.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BatchesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BatchesApi(InvoicePDFs.Client.ISynchronousClient client, InvoicePDFs.Client.IAsynchronousClient asyncClient, InvoicePDFs.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public InvoicePDFs.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public InvoicePDFs.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public InvoicePDFs.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public InvoicePDFs.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Cancel Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponse</returns>
        public BatchResponse CancelBatch(string batchId, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BatchResponse> localVarResponse = CancelBatchWithHttpInfo(batchId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BatchResponse> CancelBatchWithHttpInfo(string batchId, int operationIndex = 0)
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->CancelBatch");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter

            localVarRequestOptions.Operation = "BatchesApi.CancelBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchResponse>("/api/v1/batches/{batch_id}/cancel", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CancelBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Cancel Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponse</returns>
        public async System.Threading.Tasks.Task<BatchResponse> CancelBatchAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BatchResponse> localVarResponse = await CancelBatchWithHttpInfoAsync(batchId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Cancel Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BatchResponse>> CancelBatchWithHttpInfoAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->CancelBatch");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter

            localVarRequestOptions.Operation = "BatchesApi.CancelBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchResponse>("/api/v1/batches/{batch_id}/cancel", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CancelBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponse</returns>
        public BatchResponse CreateBatch(BatchCreateRequest batchCreateRequest, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BatchResponse> localVarResponse = CreateBatchWithHttpInfo(batchCreateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BatchResponse> CreateBatchWithHttpInfo(BatchCreateRequest batchCreateRequest, int operationIndex = 0)
        {
            // verify the required parameter 'batchCreateRequest' is set
            if (batchCreateRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchCreateRequest' when calling BatchesApi->CreateBatch");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchCreateRequest;

            localVarRequestOptions.Operation = "BatchesApi.CreateBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BatchResponse>("/api/v1/batches", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponse</returns>
        public async System.Threading.Tasks.Task<BatchResponse> CreateBatchAsync(BatchCreateRequest batchCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BatchResponse> localVarResponse = await CreateBatchWithHttpInfoAsync(batchCreateRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BatchResponse>> CreateBatchWithHttpInfoAsync(BatchCreateRequest batchCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchCreateRequest' is set
            if (batchCreateRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchCreateRequest' when calling BatchesApi->CreateBatch");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = batchCreateRequest;

            localVarRequestOptions.Operation = "BatchesApi.CreateBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BatchResponse>("/api/v1/batches", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>System.IO.Stream</returns>
        public System.IO.Stream DownloadBatch(string batchId, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<System.IO.Stream> localVarResponse = DownloadBatchWithHttpInfo(batchId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of System.IO.Stream</returns>
        public InvoicePDFs.Client.ApiResponse<System.IO.Stream> DownloadBatchWithHttpInfo(string batchId, int operationIndex = 0)
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->DownloadBatch");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/zip",
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter

            localVarRequestOptions.Operation = "BatchesApi.DownloadBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<System.IO.Stream>("/api/v1/batches/{batch_id}/download", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Download Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of System.IO.Stream</returns>
        public async System.Threading.Tasks.Task<System.IO.Stream> DownloadBatchAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<System.IO.Stream> localVarResponse = await DownloadBatchWithHttpInfoAsync(batchId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Download Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (System.IO.Stream)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<System.IO.Stream>> DownloadBatchWithHttpInfoAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->DownloadBatch");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/zip",
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter

            localVarRequestOptions.Operation = "BatchesApi.DownloadBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<System.IO.Stream>("/api/v1/batches/{batch_id}/download", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DownloadBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchResponse</returns>
        public BatchResponse GetBatch(string batchId, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BatchResponse> localVarResponse = GetBatchWithHttpInfo(batchId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BatchResponse> GetBatchWithHttpInfo(string batchId, int operationIndex = 0)
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->GetBatch");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter

            localVarRequestOptions.Operation = "BatchesApi.GetBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BatchResponse>("/api/v1/batches/{batch_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchResponse</returns>
        public async System.Threading.Tasks.Task<BatchResponse> GetBatchAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BatchResponse> localVarResponse = await GetBatchWithHttpInfoAsync(batchId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Batch 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BatchResponse>> GetBatchWithHttpInfoAsync(string batchId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->GetBatch");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter

            localVarRequestOptions.Operation = "BatchesApi.GetBatch";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<BatchResponse>("/api/v1/batches/{batch_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetBatch", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Batch Items 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchItemsListResponse</returns>
        public BatchItemsListResponse ListBatchItems(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BatchItemsListResponse> localVarResponse = ListBatchItemsWithHttpInfo(batchId, limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Batch Items 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchItemsListResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BatchItemsListResponse> ListBatchItemsWithHttpInfo(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0)
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->ListBatchItems");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "BatchesApi.ListBatchItems";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BatchItemsListResponse>("/api/v1/batches/{batch_id}/items", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBatchItems", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Batch Items 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchItemsListResponse</returns>
        public async System.Threading.Tasks.Task<BatchItemsListResponse> ListBatchItemsAsync(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BatchItemsListResponse> localVarResponse = await ListBatchItemsWithHttpInfoAsync(batchId, limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Batch Items 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="batchId"></param>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchItemsListResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BatchItemsListResponse>> ListBatchItemsWithHttpInfoAsync(string batchId, int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'batchId' is set
            if (batchId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'batchId' when calling BatchesApi->ListBatchItems");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("batch_id", InvoicePDFs.Client.ClientUtils.ParameterToString(batchId)); // path parameter
            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "BatchesApi.ListBatchItems";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<BatchItemsListResponse>("/api/v1/batches/{batch_id}/items", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBatchItems", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Batches 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BatchesListResponse</returns>
        public BatchesListResponse ListBatches(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BatchesListResponse> localVarResponse = ListBatchesWithHttpInfo(limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Batches 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BatchesListResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BatchesListResponse> ListBatchesWithHttpInfo(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "BatchesApi.ListBatches";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BatchesListResponse>("/api/v1/batches", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBatches", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Batches 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BatchesListResponse</returns>
        public async System.Threading.Tasks.Task<BatchesListResponse> ListBatchesAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BatchesListResponse> localVarResponse = await ListBatchesWithHttpInfoAsync(limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Batches 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BatchesListResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BatchesListResponse>> ListBatchesWithHttpInfoAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "BatchesApi.ListBatches";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<BatchesListResponse>("/api/v1/batches", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListBatches", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
