/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using InvoicePDFs.Client;
using InvoicePDFs.Model;

namespace InvoicePDFs.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBillingApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Checkout Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Checkout session for a subscription.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingCheckoutResponse</returns>
        BillingCheckoutResponse CreateCheckoutSession(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0);

        /// <summary>
        /// Create Checkout Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Checkout session for a subscription.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingCheckoutResponse</returns>
        ApiResponse<BillingCheckoutResponse> CreateCheckoutSessionWithHttpInfo(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0);
        /// <summary>
        /// Create Portal Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Customer Portal session for self-service management.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingPortalResponse</returns>
        BillingPortalResponse CreatePortalSession(int operationIndex = 0);

        /// <summary>
        /// Create Portal Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Customer Portal session for self-service management.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingPortalResponse</returns>
        ApiResponse<BillingPortalResponse> CreatePortalSessionWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get current subscription status (from DB, no Stripe API call).
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingSubscriptionResponse</returns>
        BillingSubscriptionResponse GetSubscription(int operationIndex = 0);

        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get current subscription status (from DB, no Stripe API call).
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingSubscriptionResponse</returns>
        ApiResponse<BillingSubscriptionResponse> GetSubscriptionWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// List Plans
        /// </summary>
        /// <remarks>
        /// Purchasable plans — the ones wired to a Stripe price.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingPlansListResponse</returns>
        BillingPlansListResponse ListPlans(int operationIndex = 0);

        /// <summary>
        /// List Plans
        /// </summary>
        /// <remarks>
        /// Purchasable plans — the ones wired to a Stripe price.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingPlansListResponse</returns>
        ApiResponse<BillingPlansListResponse> ListPlansWithHttpInfo(int operationIndex = 0);
        /// <summary>
        /// Update Overage Settings
        /// </summary>
        /// <remarks>
        /// Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingOverageResponse</returns>
        BillingOverageResponse UpdateOverageSettings(BillingOverageRequest billingOverageRequest, int operationIndex = 0);

        /// <summary>
        /// Update Overage Settings
        /// </summary>
        /// <remarks>
        /// Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingOverageResponse</returns>
        ApiResponse<BillingOverageResponse> UpdateOverageSettingsWithHttpInfo(BillingOverageRequest billingOverageRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBillingApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Checkout Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Checkout session for a subscription.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingCheckoutResponse</returns>
        System.Threading.Tasks.Task<BillingCheckoutResponse> CreateCheckoutSessionAsync(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Checkout Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Checkout session for a subscription.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingCheckoutResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BillingCheckoutResponse>> CreateCheckoutSessionWithHttpInfoAsync(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Create Portal Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Customer Portal session for self-service management.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingPortalResponse</returns>
        System.Threading.Tasks.Task<BillingPortalResponse> CreatePortalSessionAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Portal Session
        /// </summary>
        /// <remarks>
        /// Create a Stripe Customer Portal session for self-service management.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingPortalResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BillingPortalResponse>> CreatePortalSessionWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get current subscription status (from DB, no Stripe API call).
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingSubscriptionResponse</returns>
        System.Threading.Tasks.Task<BillingSubscriptionResponse> GetSubscriptionAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Subscription
        /// </summary>
        /// <remarks>
        /// Get current subscription status (from DB, no Stripe API call).
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingSubscriptionResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BillingSubscriptionResponse>> GetSubscriptionWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Plans
        /// </summary>
        /// <remarks>
        /// Purchasable plans — the ones wired to a Stripe price.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingPlansListResponse</returns>
        System.Threading.Tasks.Task<BillingPlansListResponse> ListPlansAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Plans
        /// </summary>
        /// <remarks>
        /// Purchasable plans — the ones wired to a Stripe price.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingPlansListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BillingPlansListResponse>> ListPlansWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Overage Settings
        /// </summary>
        /// <remarks>
        /// Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingOverageResponse</returns>
        System.Threading.Tasks.Task<BillingOverageResponse> UpdateOverageSettingsAsync(BillingOverageRequest billingOverageRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update Overage Settings
        /// </summary>
        /// <remarks>
        /// Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingOverageResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<BillingOverageResponse>> UpdateOverageSettingsWithHttpInfoAsync(BillingOverageRequest billingOverageRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface IBillingApi : IBillingApiSync, IBillingApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class BillingApi : IBillingApi
    {
        private InvoicePDFs.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BillingApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class.
        /// </summary>
        /// <returns></returns>
        public BillingApi(string basePath)
        {
            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                new InvoicePDFs.Client.Configuration { BasePath = basePath }
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public BillingApi(InvoicePDFs.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="BillingApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public BillingApi(InvoicePDFs.Client.ISynchronousClient client, InvoicePDFs.Client.IAsynchronousClient asyncClient, InvoicePDFs.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public InvoicePDFs.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public InvoicePDFs.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public InvoicePDFs.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public InvoicePDFs.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Checkout Session Create a Stripe Checkout session for a subscription.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingCheckoutResponse</returns>
        public BillingCheckoutResponse CreateCheckoutSession(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BillingCheckoutResponse> localVarResponse = CreateCheckoutSessionWithHttpInfo(billingCheckoutRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Checkout Session Create a Stripe Checkout session for a subscription.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingCheckoutResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BillingCheckoutResponse> CreateCheckoutSessionWithHttpInfo(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0)
        {
            // verify the required parameter 'billingCheckoutRequest' is set
            if (billingCheckoutRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'billingCheckoutRequest' when calling BillingApi->CreateCheckoutSession");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = billingCheckoutRequest;

            localVarRequestOptions.Operation = "BillingApi.CreateCheckoutSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BillingCheckoutResponse>("/api/v1/billing/checkout-session", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCheckoutSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Checkout Session Create a Stripe Checkout session for a subscription.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingCheckoutResponse</returns>
        public async System.Threading.Tasks.Task<BillingCheckoutResponse> CreateCheckoutSessionAsync(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BillingCheckoutResponse> localVarResponse = await CreateCheckoutSessionWithHttpInfoAsync(billingCheckoutRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Checkout Session Create a Stripe Checkout session for a subscription.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingCheckoutRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingCheckoutResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BillingCheckoutResponse>> CreateCheckoutSessionWithHttpInfoAsync(BillingCheckoutRequest billingCheckoutRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'billingCheckoutRequest' is set
            if (billingCheckoutRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'billingCheckoutRequest' when calling BillingApi->CreateCheckoutSession");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = billingCheckoutRequest;

            localVarRequestOptions.Operation = "BillingApi.CreateCheckoutSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BillingCheckoutResponse>("/api/v1/billing/checkout-session", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateCheckoutSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Portal Session Create a Stripe Customer Portal session for self-service management.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingPortalResponse</returns>
        public BillingPortalResponse CreatePortalSession(int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BillingPortalResponse> localVarResponse = CreatePortalSessionWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Portal Session Create a Stripe Customer Portal session for self-service management.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingPortalResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BillingPortalResponse> CreatePortalSessionWithHttpInfo(int operationIndex = 0)
        {
            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BillingApi.CreatePortalSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<BillingPortalResponse>("/api/v1/billing/portal-session", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePortalSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Portal Session Create a Stripe Customer Portal session for self-service management.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingPortalResponse</returns>
        public async System.Threading.Tasks.Task<BillingPortalResponse> CreatePortalSessionAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BillingPortalResponse> localVarResponse = await CreatePortalSessionWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Portal Session Create a Stripe Customer Portal session for self-service management.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingPortalResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BillingPortalResponse>> CreatePortalSessionWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BillingApi.CreatePortalSession";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<BillingPortalResponse>("/api/v1/billing/portal-session", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreatePortalSession", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Subscription Get current subscription status (from DB, no Stripe API call).
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingSubscriptionResponse</returns>
        public BillingSubscriptionResponse GetSubscription(int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BillingSubscriptionResponse> localVarResponse = GetSubscriptionWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Subscription Get current subscription status (from DB, no Stripe API call).
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingSubscriptionResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BillingSubscriptionResponse> GetSubscriptionWithHttpInfo(int operationIndex = 0)
        {
            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BillingApi.GetSubscription";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BillingSubscriptionResponse>("/api/v1/billing/subscription", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSubscription", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Subscription Get current subscription status (from DB, no Stripe API call).
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingSubscriptionResponse</returns>
        public async System.Threading.Tasks.Task<BillingSubscriptionResponse> GetSubscriptionAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BillingSubscriptionResponse> localVarResponse = await GetSubscriptionWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Subscription Get current subscription status (from DB, no Stripe API call).
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingSubscriptionResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BillingSubscriptionResponse>> GetSubscriptionWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BillingApi.GetSubscription";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<BillingSubscriptionResponse>("/api/v1/billing/subscription", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetSubscription", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Plans Purchasable plans — the ones wired to a Stripe price.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingPlansListResponse</returns>
        public BillingPlansListResponse ListPlans(int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BillingPlansListResponse> localVarResponse = ListPlansWithHttpInfo();
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Plans Purchasable plans — the ones wired to a Stripe price.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingPlansListResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BillingPlansListResponse> ListPlansWithHttpInfo(int operationIndex = 0)
        {
            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BillingApi.ListPlans";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<BillingPlansListResponse>("/api/v1/billing/plans", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPlans", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Plans Purchasable plans — the ones wired to a Stripe price.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingPlansListResponse</returns>
        public async System.Threading.Tasks.Task<BillingPlansListResponse> ListPlansAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BillingPlansListResponse> localVarResponse = await ListPlansWithHttpInfoAsync(operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Plans Purchasable plans — the ones wired to a Stripe price.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingPlansListResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BillingPlansListResponse>> ListPlansWithHttpInfoAsync(int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }


            localVarRequestOptions.Operation = "BillingApi.ListPlans";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<BillingPlansListResponse>("/api/v1/billing/plans", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListPlans", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Overage Settings Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>BillingOverageResponse</returns>
        public BillingOverageResponse UpdateOverageSettings(BillingOverageRequest billingOverageRequest, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<BillingOverageResponse> localVarResponse = UpdateOverageSettingsWithHttpInfo(billingOverageRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Overage Settings Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of BillingOverageResponse</returns>
        public InvoicePDFs.Client.ApiResponse<BillingOverageResponse> UpdateOverageSettingsWithHttpInfo(BillingOverageRequest billingOverageRequest, int operationIndex = 0)
        {
            // verify the required parameter 'billingOverageRequest' is set
            if (billingOverageRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'billingOverageRequest' when calling BillingApi->UpdateOverageSettings");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = billingOverageRequest;

            localVarRequestOptions.Operation = "BillingApi.UpdateOverageSettings";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<BillingOverageResponse>("/api/v1/billing/overage", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateOverageSettings", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Overage Settings Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of BillingOverageResponse</returns>
        public async System.Threading.Tasks.Task<BillingOverageResponse> UpdateOverageSettingsAsync(BillingOverageRequest billingOverageRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<BillingOverageResponse> localVarResponse = await UpdateOverageSettingsWithHttpInfoAsync(billingOverageRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Overage Settings Turn overage billing on or off for this account.  Off by default and stays off until asked: past the quota the API returns 429, which is a limit the customer can see coming. Overage replaces that limit with a charge, and nobody should meet that decision on an invoice.
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="billingOverageRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (BillingOverageResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<BillingOverageResponse>> UpdateOverageSettingsWithHttpInfoAsync(BillingOverageRequest billingOverageRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'billingOverageRequest' is set
            if (billingOverageRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'billingOverageRequest' when calling BillingApi->UpdateOverageSettings");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = billingOverageRequest;

            localVarRequestOptions.Operation = "BillingApi.UpdateOverageSettings";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<BillingOverageResponse>("/api/v1/billing/overage", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateOverageSettings", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
