/*
 * InvoicePDFs
 *
 * InvoicePDFs turns a JSON document into a polished PDF — invoices, credit notes, quotes, receipts, proformas, purchase orders and delivery notes. The API validates your data, computes totals correctly (tax, discounts, shipping), and returns a downloadable, professional PDF.  This package is the official client for the InvoicePDFs API, generated from the OpenAPI specification.  Documentation: https://invoicepdfs.com
 *
 * The version of the OpenAPI document: 0.3.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Net;
using System.Net.Mime;
using InvoicePDFs.Client;
using InvoicePDFs.Model;

namespace InvoicePDFs.Api
{

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxRatesApiSync : IApiAccessor
    {
        #region Synchronous Operations
        /// <summary>
        /// Create Tax Rate
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRateResponse</returns>
        TaxRateResponse CreateTaxRate(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0);

        /// <summary>
        /// Create Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRateResponse</returns>
        ApiResponse<TaxRateResponse> CreateTaxRateWithHttpInfo(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0);
        /// <summary>
        /// Delete Tax Rate
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SimpleBoolResponse</returns>
        SimpleBoolResponse DeleteTaxRate(string taxRateId, int operationIndex = 0);

        /// <summary>
        /// Delete Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SimpleBoolResponse</returns>
        ApiResponse<SimpleBoolResponse> DeleteTaxRateWithHttpInfo(string taxRateId, int operationIndex = 0);
        /// <summary>
        /// Get Tax Rate
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRateResponse</returns>
        TaxRateResponse GetTaxRate(string taxRateId, int operationIndex = 0);

        /// <summary>
        /// Get Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRateResponse</returns>
        ApiResponse<TaxRateResponse> GetTaxRateWithHttpInfo(string taxRateId, int operationIndex = 0);
        /// <summary>
        /// List Tax Rates
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRatesListResponse</returns>
        TaxRatesListResponse ListTaxRates(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0);

        /// <summary>
        /// List Tax Rates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRatesListResponse</returns>
        ApiResponse<TaxRatesListResponse> ListTaxRatesWithHttpInfo(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0);
        /// <summary>
        /// Update Tax Rate
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRateResponse</returns>
        TaxRateResponse UpdateTaxRate(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0);

        /// <summary>
        /// Update Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRateResponse</returns>
        ApiResponse<TaxRateResponse> UpdateTaxRateWithHttpInfo(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0);
        #endregion Synchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxRatesApiAsync : IApiAccessor
    {
        #region Asynchronous Operations
        /// <summary>
        /// Create Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRateResponse</returns>
        System.Threading.Tasks.Task<TaxRateResponse> CreateTaxRateAsync(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Create Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaxRateResponse>> CreateTaxRateWithHttpInfoAsync(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Delete Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SimpleBoolResponse</returns>
        System.Threading.Tasks.Task<SimpleBoolResponse> DeleteTaxRateAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Delete Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SimpleBoolResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<SimpleBoolResponse>> DeleteTaxRateWithHttpInfoAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Get Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRateResponse</returns>
        System.Threading.Tasks.Task<TaxRateResponse> GetTaxRateAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Get Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaxRateResponse>> GetTaxRateWithHttpInfoAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// List Tax Rates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRatesListResponse</returns>
        System.Threading.Tasks.Task<TaxRatesListResponse> ListTaxRatesAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// List Tax Rates
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRatesListResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaxRatesListResponse>> ListTaxRatesWithHttpInfoAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        /// <summary>
        /// Update Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRateResponse</returns>
        System.Threading.Tasks.Task<TaxRateResponse> UpdateTaxRateAsync(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));

        /// <summary>
        /// Update Tax Rate
        /// </summary>
        /// <remarks>
        /// 
        /// </remarks>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRateResponse)</returns>
        System.Threading.Tasks.Task<ApiResponse<TaxRateResponse>> UpdateTaxRateWithHttpInfoAsync(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken));
        #endregion Asynchronous Operations
    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public interface ITaxRatesApi : ITaxRatesApiSync, ITaxRatesApiAsync
    {

    }

    /// <summary>
    /// Represents a collection of functions to interact with the API endpoints
    /// </summary>
    public partial class TaxRatesApi : ITaxRatesApi
    {
        private InvoicePDFs.Client.ExceptionFactory _exceptionFactory = (name, response) => null;

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxRatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaxRatesApi() : this((string)null)
        {
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxRatesApi"/> class.
        /// </summary>
        /// <returns></returns>
        public TaxRatesApi(string basePath)
        {
            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                new InvoicePDFs.Client.Configuration { BasePath = basePath }
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxRatesApi"/> class
        /// using Configuration object
        /// </summary>
        /// <param name="configuration">An instance of Configuration</param>
        /// <returns></returns>
        public TaxRatesApi(InvoicePDFs.Client.Configuration configuration)
        {
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Configuration = InvoicePDFs.Client.Configuration.MergeConfigurations(
                InvoicePDFs.Client.GlobalConfiguration.Instance,
                configuration
            );
            this.Client = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            this.AsynchronousClient = new InvoicePDFs.Client.ApiClient(this.Configuration.BasePath);
            ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="TaxRatesApi"/> class
        /// using a Configuration object and client instance.
        /// </summary>
        /// <param name="client">The client interface for synchronous API access.</param>
        /// <param name="asyncClient">The client interface for asynchronous API access.</param>
        /// <param name="configuration">The configuration object.</param>
        public TaxRatesApi(InvoicePDFs.Client.ISynchronousClient client, InvoicePDFs.Client.IAsynchronousClient asyncClient, InvoicePDFs.Client.IReadableConfiguration configuration)
        {
            if (client == null) throw new ArgumentNullException("client");
            if (asyncClient == null) throw new ArgumentNullException("asyncClient");
            if (configuration == null) throw new ArgumentNullException("configuration");

            this.Client = client;
            this.AsynchronousClient = asyncClient;
            this.Configuration = configuration;
            this.ExceptionFactory = InvoicePDFs.Client.Configuration.DefaultExceptionFactory;
        }

        /// <summary>
        /// The client for accessing this underlying API asynchronously.
        /// </summary>
        public InvoicePDFs.Client.IAsynchronousClient AsynchronousClient { get; set; }

        /// <summary>
        /// The client for accessing this underlying API synchronously.
        /// </summary>
        public InvoicePDFs.Client.ISynchronousClient Client { get; set; }

        /// <summary>
        /// Gets the base path of the API client.
        /// </summary>
        /// <value>The base path</value>
        public string GetBasePath()
        {
            return this.Configuration.BasePath;
        }

        /// <summary>
        /// Gets or sets the configuration object
        /// </summary>
        /// <value>An instance of the Configuration</value>
        public InvoicePDFs.Client.IReadableConfiguration Configuration { get; set; }

        /// <summary>
        /// Provides a factory method hook for the creation of exceptions.
        /// </summary>
        public InvoicePDFs.Client.ExceptionFactory ExceptionFactory
        {
            get
            {
                if (_exceptionFactory != null && _exceptionFactory.GetInvocationList().Length > 1)
                {
                    throw new InvalidOperationException("Multicast delegate for ExceptionFactory is unsupported.");
                }
                return _exceptionFactory;
            }
            set { _exceptionFactory = value; }
        }

        /// <summary>
        /// Create Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRateResponse</returns>
        public TaxRateResponse CreateTaxRate(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<TaxRateResponse> localVarResponse = CreateTaxRateWithHttpInfo(taxRateCreateRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRateResponse</returns>
        public InvoicePDFs.Client.ApiResponse<TaxRateResponse> CreateTaxRateWithHttpInfo(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0)
        {
            // verify the required parameter 'taxRateCreateRequest' is set
            if (taxRateCreateRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateCreateRequest' when calling TaxRatesApi->CreateTaxRate");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = taxRateCreateRequest;

            localVarRequestOptions.Operation = "TaxRatesApi.CreateTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Post<TaxRateResponse>("/api/v1/tax-rates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Create Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRateResponse</returns>
        public async System.Threading.Tasks.Task<TaxRateResponse> CreateTaxRateAsync(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<TaxRateResponse> localVarResponse = await CreateTaxRateWithHttpInfoAsync(taxRateCreateRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Create Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateCreateRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRateResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<TaxRateResponse>> CreateTaxRateWithHttpInfoAsync(TaxRateCreateRequest taxRateCreateRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'taxRateCreateRequest' is set
            if (taxRateCreateRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateCreateRequest' when calling TaxRatesApi->CreateTaxRate");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.Data = taxRateCreateRequest;

            localVarRequestOptions.Operation = "TaxRatesApi.CreateTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PostAsync<TaxRateResponse>("/api/v1/tax-rates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("CreateTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>SimpleBoolResponse</returns>
        public SimpleBoolResponse DeleteTaxRate(string taxRateId, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<SimpleBoolResponse> localVarResponse = DeleteTaxRateWithHttpInfo(taxRateId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of SimpleBoolResponse</returns>
        public InvoicePDFs.Client.ApiResponse<SimpleBoolResponse> DeleteTaxRateWithHttpInfo(string taxRateId, int operationIndex = 0)
        {
            // verify the required parameter 'taxRateId' is set
            if (taxRateId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateId' when calling TaxRatesApi->DeleteTaxRate");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tax_rate_id", InvoicePDFs.Client.ClientUtils.ParameterToString(taxRateId)); // path parameter

            localVarRequestOptions.Operation = "TaxRatesApi.DeleteTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Delete<SimpleBoolResponse>("/api/v1/tax-rates/{tax_rate_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Delete Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of SimpleBoolResponse</returns>
        public async System.Threading.Tasks.Task<SimpleBoolResponse> DeleteTaxRateAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<SimpleBoolResponse> localVarResponse = await DeleteTaxRateWithHttpInfoAsync(taxRateId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Delete Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (SimpleBoolResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<SimpleBoolResponse>> DeleteTaxRateWithHttpInfoAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'taxRateId' is set
            if (taxRateId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateId' when calling TaxRatesApi->DeleteTaxRate");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tax_rate_id", InvoicePDFs.Client.ClientUtils.ParameterToString(taxRateId)); // path parameter

            localVarRequestOptions.Operation = "TaxRatesApi.DeleteTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.DeleteAsync<SimpleBoolResponse>("/api/v1/tax-rates/{tax_rate_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("DeleteTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRateResponse</returns>
        public TaxRateResponse GetTaxRate(string taxRateId, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<TaxRateResponse> localVarResponse = GetTaxRateWithHttpInfo(taxRateId);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRateResponse</returns>
        public InvoicePDFs.Client.ApiResponse<TaxRateResponse> GetTaxRateWithHttpInfo(string taxRateId, int operationIndex = 0)
        {
            // verify the required parameter 'taxRateId' is set
            if (taxRateId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateId' when calling TaxRatesApi->GetTaxRate");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tax_rate_id", InvoicePDFs.Client.ClientUtils.ParameterToString(taxRateId)); // path parameter

            localVarRequestOptions.Operation = "TaxRatesApi.GetTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TaxRateResponse>("/api/v1/tax-rates/{tax_rate_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Get Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRateResponse</returns>
        public async System.Threading.Tasks.Task<TaxRateResponse> GetTaxRateAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<TaxRateResponse> localVarResponse = await GetTaxRateWithHttpInfoAsync(taxRateId, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Get Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRateResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<TaxRateResponse>> GetTaxRateWithHttpInfoAsync(string taxRateId, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'taxRateId' is set
            if (taxRateId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateId' when calling TaxRatesApi->GetTaxRate");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tax_rate_id", InvoicePDFs.Client.ClientUtils.ParameterToString(taxRateId)); // path parameter

            localVarRequestOptions.Operation = "TaxRatesApi.GetTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TaxRateResponse>("/api/v1/tax-rates/{tax_rate_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("GetTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Tax Rates 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRatesListResponse</returns>
        public TaxRatesListResponse ListTaxRates(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<TaxRatesListResponse> localVarResponse = ListTaxRatesWithHttpInfo(limit, cursor);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Tax Rates 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRatesListResponse</returns>
        public InvoicePDFs.Client.ApiResponse<TaxRatesListResponse> ListTaxRatesWithHttpInfo(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0)
        {
            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "TaxRatesApi.ListTaxRates";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Get<TaxRatesListResponse>("/api/v1/tax-rates", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTaxRates", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// List Tax Rates 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRatesListResponse</returns>
        public async System.Threading.Tasks.Task<TaxRatesListResponse> ListTaxRatesAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<TaxRatesListResponse> localVarResponse = await ListTaxRatesWithHttpInfoAsync(limit, cursor, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// List Tax Rates 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="limit"> (optional, default to 50)</param>
        /// <param name="cursor"> (optional)</param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRatesListResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<TaxRatesListResponse>> ListTaxRatesWithHttpInfoAsync(int? limit = default(int?), string? cursor = default(string?), int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            if (limit != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "limit", limit));
            }
            if (cursor != null)
            {
                localVarRequestOptions.QueryParameters.Add(InvoicePDFs.Client.ClientUtils.ParameterToMultiMap("", "cursor", cursor));
            }

            localVarRequestOptions.Operation = "TaxRatesApi.ListTaxRates";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.GetAsync<TaxRatesListResponse>("/api/v1/tax-rates", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("ListTaxRates", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>TaxRateResponse</returns>
        public TaxRateResponse UpdateTaxRate(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0)
        {
            InvoicePDFs.Client.ApiResponse<TaxRateResponse> localVarResponse = UpdateTaxRateWithHttpInfo(taxRateId, taxRatePatchRequest);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <returns>ApiResponse of TaxRateResponse</returns>
        public InvoicePDFs.Client.ApiResponse<TaxRateResponse> UpdateTaxRateWithHttpInfo(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0)
        {
            // verify the required parameter 'taxRateId' is set
            if (taxRateId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateId' when calling TaxRatesApi->UpdateTaxRate");
            }

            // verify the required parameter 'taxRatePatchRequest' is set
            if (taxRatePatchRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRatePatchRequest' when calling TaxRatesApi->UpdateTaxRate");
            }

            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tax_rate_id", InvoicePDFs.Client.ClientUtils.ParameterToString(taxRateId)); // path parameter
            localVarRequestOptions.Data = taxRatePatchRequest;

            localVarRequestOptions.Operation = "TaxRatesApi.UpdateTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = this.Client.Patch<TaxRateResponse>("/api/v1/tax-rates/{tax_rate_id}", localVarRequestOptions, this.Configuration);
            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

        /// <summary>
        /// Update Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of TaxRateResponse</returns>
        public async System.Threading.Tasks.Task<TaxRateResponse> UpdateTaxRateAsync(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            InvoicePDFs.Client.ApiResponse<TaxRateResponse> localVarResponse = await UpdateTaxRateWithHttpInfoAsync(taxRateId, taxRatePatchRequest, operationIndex, cancellationToken).ConfigureAwait(false);
            return localVarResponse.Data;
        }

        /// <summary>
        /// Update Tax Rate 
        /// </summary>
        /// <exception cref="InvoicePDFs.Client.ApiException">Thrown when fails to make API call</exception>
        /// <param name="taxRateId"></param>
        /// <param name="taxRatePatchRequest"></param>
        /// <param name="operationIndex">Index associated with the operation.</param>
        /// <param name="cancellationToken">Cancellation Token to cancel the request.</param>
        /// <returns>Task of ApiResponse (TaxRateResponse)</returns>
        public async System.Threading.Tasks.Task<InvoicePDFs.Client.ApiResponse<TaxRateResponse>> UpdateTaxRateWithHttpInfoAsync(string taxRateId, TaxRatePatchRequest taxRatePatchRequest, int operationIndex = 0, System.Threading.CancellationToken cancellationToken = default(System.Threading.CancellationToken))
        {
            // verify the required parameter 'taxRateId' is set
            if (taxRateId == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRateId' when calling TaxRatesApi->UpdateTaxRate");
            }

            // verify the required parameter 'taxRatePatchRequest' is set
            if (taxRatePatchRequest == null)
            {
                throw new InvoicePDFs.Client.ApiException(400, "Missing required parameter 'taxRatePatchRequest' when calling TaxRatesApi->UpdateTaxRate");
            }


            InvoicePDFs.Client.RequestOptions localVarRequestOptions = new InvoicePDFs.Client.RequestOptions();

            string[] _contentTypes = new string[] {
                "application/json"
            };

            // to determine the Accept header
            string[] _accepts = new string[] {
                "application/json"
            };

            var localVarContentType = InvoicePDFs.Client.ClientUtils.SelectHeaderContentType(_contentTypes);
            if (localVarContentType != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Content-Type", localVarContentType);
            }

            var localVarAccept = InvoicePDFs.Client.ClientUtils.SelectHeaderAccept(_accepts);
            if (localVarAccept != null)
            {
                localVarRequestOptions.HeaderParameters.Add("Accept", localVarAccept);
            }

            localVarRequestOptions.PathParameters.Add("tax_rate_id", InvoicePDFs.Client.ClientUtils.ParameterToString(taxRateId)); // path parameter
            localVarRequestOptions.Data = taxRatePatchRequest;

            localVarRequestOptions.Operation = "TaxRatesApi.UpdateTaxRate";
            localVarRequestOptions.OperationIndex = operationIndex;

            // authentication (HTTPBearer) required
            // bearer authentication required
            if (!string.IsNullOrEmpty(this.Configuration.AccessToken) && !localVarRequestOptions.HeaderParameters.ContainsKey("Authorization"))
            {
                localVarRequestOptions.HeaderParameters.Add("Authorization", "Bearer " + this.Configuration.AccessToken);
            }

            // make the HTTP request
            var localVarResponse = await this.AsynchronousClient.PatchAsync<TaxRateResponse>("/api/v1/tax-rates/{tax_rate_id}", localVarRequestOptions, this.Configuration, cancellationToken).ConfigureAwait(false);

            if (this.ExceptionFactory != null)
            {
                Exception _exception = this.ExceptionFactory("UpdateTaxRate", localVarResponse);
                if (_exception != null)
                {
                    throw _exception;
                }
            }

            return localVarResponse;
        }

    }
}
